# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_manager_grpc_pb2 as agent__manager__grpc__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_manager_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAgent = channel.unary_unary(
                '/agent_manager_grpc.AgentManagerService/RunAgent',
                request_serializer=agent__manager__grpc__pb2.RunAgentRequest.SerializeToString,
                response_deserializer=agent__manager__grpc__pb2.AgentOutput.FromString,
                _registered_method=True)
        self.RunAgentStream = channel.unary_stream(
                '/agent_manager_grpc.AgentManagerService/RunAgentStream',
                request_serializer=agent__manager__grpc__pb2.RunAgentRequest.SerializeToString,
                response_deserializer=agent__manager__grpc__pb2.RunAgentResponseStreamChunk.FromString,
                _registered_method=True)


class AgentManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunAgentStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAgent,
                    request_deserializer=agent__manager__grpc__pb2.RunAgentRequest.FromString,
                    response_serializer=agent__manager__grpc__pb2.AgentOutput.SerializeToString,
            ),
            'RunAgentStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAgentStream,
                    request_deserializer=agent__manager__grpc__pb2.RunAgentRequest.FromString,
                    response_serializer=agent__manager__grpc__pb2.RunAgentResponseStreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_manager_grpc.AgentManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_manager_grpc.AgentManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_manager_grpc.AgentManagerService/RunAgent',
            agent__manager__grpc__pb2.RunAgentRequest.SerializeToString,
            agent__manager__grpc__pb2.AgentOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunAgentStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent_manager_grpc.AgentManagerService/RunAgentStream',
            agent__manager__grpc__pb2.RunAgentRequest.SerializeToString,
            agent__manager__grpc__pb2.RunAgentResponseStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
