//! ClickHouse SQL → JSON-query-structure conversion for the in-process query
//! engine. Ported from `query-engine/src/sql_to_json.py`.
//!
//! This is a best-effort structural parse used to round-trip a chart query back
//! into its declarative form for the chart builder UI. It is NOT a security
//! boundary (the SQL it parses was generated by `convert_json_to_sql` or typed
//! into the SQL editor, which is separately validated).

use sqlparser::ast::{
    BinaryOperator, Expr, Function, FunctionArg, FunctionArgExpr, FunctionArguments, GroupByExpr,
    LimitClause, ObjectName, ObjectNamePart, OrderByExpr, OrderByKind, Query, Select, SelectItem,
    SetExpr, Statement, Value,
};
use sqlparser::dialect::ClickHouseDialect;
use sqlparser::parser::Parser;
use std::collections::HashSet;

use super::types::{Filter, FilterValue, Metric, OrderBy, QueryStructure, TimeRange};

const DEFAULT_START_TIME: &str = "{start_time:DateTime64}";
const DEFAULT_END_TIME: &str = "{end_time:DateTime64}";

pub fn convert_sql_to_json(sql: &str) -> Result<QueryStructure, String> {
    let dialect = ClickHouseDialect {};
    let mut statements =
        Parser::parse_sql(&dialect, sql).map_err(|e| format!("Failed to parse SQL: {e}"))?;

    if statements.len() != 1 {
        return Err("Only SELECT queries supported".to_string());
    }

    let query = match statements.remove(0) {
        Statement::Query(query) => query,
        _ => return Err("Only SELECT queries supported".to_string()),
    };

    let select = match query.body.as_ref() {
        SetExpr::Select(select) => select.as_ref(),
        _ => return Err("Only SELECT queries supported".to_string()),
    };

    let table = select_table_name(select)?;
    let grouped_columns = get_grouped_columns(select);

    let (metrics, dimensions, time_range) =
        parse_select_expressions(select, &query, &grouped_columns);
    let filters = parse_where_clause(select, time_range.as_ref());
    let order_by = parse_order_by_clause(&query);
    let limit = parse_limit_clause(&query);

    Ok(QueryStructure {
        table,
        metrics,
        dimensions,
        filters,
        time_range,
        order_by,
        limit,
    })
}

fn select_table_name(select: &Select) -> Result<String, String> {
    let first = select
        .from
        .first()
        .ok_or_else(|| "Query must have a FROM clause".to_string())?;
    match &first.relation {
        sqlparser::ast::TableFactor::Table { name, .. } => Ok(object_name_last(name)),
        _ => Err("Unsupported FROM clause".to_string()),
    }
}

fn object_name_last(name: &ObjectName) -> String {
    name.0
        .last()
        .map(object_name_part_ident)
        .unwrap_or_default()
}

fn object_name_part_ident(part: &ObjectNamePart) -> String {
    match part {
        ObjectNamePart::Identifier(ident) => ident.value.clone(),
        other => other.to_string(),
    }
}

fn function_name(f: &Function) -> String {
    object_name_last(&f.name)
}

fn get_grouped_columns(select: &Select) -> HashSet<String> {
    let mut grouped = HashSet::new();
    if let GroupByExpr::Expressions(exprs, _) = &select.group_by {
        for expr in exprs {
            match expr {
                Expr::Identifier(ident) => {
                    grouped.insert(ident.value.clone());
                }
                Expr::CompoundIdentifier(parts) => {
                    if let Some(last) = parts.last() {
                        grouped.insert(last.value.clone());
                    }
                }
                other => {
                    grouped.insert(other.to_string());
                }
            }
        }
    }
    grouped
}

fn column_name(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Identifier(ident) => Some(ident.value.clone()),
        Expr::CompoundIdentifier(parts) => parts.last().map(|p| p.value.clone()),
        _ => None,
    }
}

fn is_time_bucket(expr: &Expr) -> bool {
    matches!(expr, Expr::Function(f) if function_name(f).to_uppercase() == "TOSTARTOFINTERVAL")
}

fn parse_select_expressions(
    select: &Select,
    query: &Query,
    grouped_columns: &HashSet<String>,
) -> (Vec<Metric>, Vec<String>, Option<TimeRange>) {
    let mut metrics = Vec::new();
    let mut dimensions = Vec::new();
    let mut time_range = None;

    for item in &select.projection {
        match item {
            SelectItem::ExprWithAlias { expr, alias } => {
                let alias_str = alias.value.clone();
                if is_time_bucket(expr) {
                    time_range = Some(extract_time_range(select, query, expr));
                } else if grouped_columns.contains(&alias_str)
                    || is_simple_column_ref(expr, grouped_columns)
                {
                    if let Some(name) = column_name(expr) {
                        dimensions.push(name);
                    }
                } else {
                    metrics.push(extract_metric(expr, &alias_str));
                }
            }
            SelectItem::UnnamedExpr(expr) => {
                if let Some(name) = column_name(expr) {
                    dimensions.push(name);
                }
            }
            _ => {}
        }
    }

    (metrics, dimensions, time_range)
}

fn is_simple_column_ref(expr: &Expr, grouped_columns: &HashSet<String>) -> bool {
    match column_name(expr) {
        Some(name) => grouped_columns.contains(&name),
        None => grouped_columns.contains(&expr.to_string()),
    }
}

/// Extract a metric from a projection expression. Detects standard aggregates
/// and quantile by the top-level function name only; anything else (including
/// compound expressions like `countIf(...) / count(*)`) becomes a `raw` metric.
pub(crate) fn extract_metric(expr: &Expr, alias: &str) -> Metric {
    let mut inner = expr;
    while let Expr::Nested(e) = inner {
        inner = e;
    }

    if let Expr::Function(f) = inner {
        let fn_lower = function_name(f).to_lowercase();
        match fn_lower.as_str() {
            "quantile" => return parse_quantile(f, alias),
            "count" | "sum" | "avg" | "min" | "max" => {
                return parse_standard_agg(f, &fn_lower, alias);
            }
            _ => {}
        }
    }

    Metric {
        r#fn: "raw".to_string(),
        column: inner.to_string(),
        args: vec![],
        alias: Some(alias.to_string()),
    }
}

fn function_args(f: &Function) -> &[FunctionArg] {
    match &f.args {
        FunctionArguments::List(list) => &list.args,
        _ => &[],
    }
}

fn function_first_arg_column(f: &Function, default: &str) -> String {
    match function_args(f).first() {
        Some(FunctionArg::Unnamed(FunctionArgExpr::Wildcard)) => "*".to_string(),
        Some(FunctionArg::Unnamed(FunctionArgExpr::Expr(e))) => extract_column(e),
        Some(FunctionArg::Named { arg, .. }) | Some(FunctionArg::ExprNamed { arg, .. }) => {
            match arg {
                FunctionArgExpr::Wildcard => "*".to_string(),
                FunctionArgExpr::Expr(e) => extract_column(e),
                _ => default.to_string(),
            }
        }
        _ => default.to_string(),
    }
}

fn extract_column(expr: &Expr) -> String {
    match expr {
        Expr::Identifier(ident) => ident.value.clone(),
        Expr::CompoundIdentifier(parts) => {
            parts.last().map(|p| p.value.clone()).unwrap_or_default()
        }
        _ => expr.to_string(),
    }
}

fn parse_quantile(f: &Function, alias: &str) -> Metric {
    let column = function_first_arg_column(f, "unknown");

    let mut percentile = 0.5;
    if let FunctionArguments::List(list) = &f.parameters {
        if let Some(FunctionArg::Unnamed(FunctionArgExpr::Expr(Expr::Value(v)))) = list.args.first()
        {
            if let Value::Number(n, _) = &v.value {
                if let Ok(parsed) = n.parse::<f64>() {
                    percentile = parsed;
                }
            }
        }
    }

    Metric {
        r#fn: "quantile".to_string(),
        column,
        args: vec![percentile],
        alias: Some(alias.to_string()),
    }
}

fn parse_standard_agg(f: &Function, fn_name: &str, alias: &str) -> Metric {
    let column = function_first_arg_column(f, "*");
    Metric {
        r#fn: fn_name.to_string(),
        column,
        args: vec![],
        alias: Some(alias.to_string()),
    }
}

fn extract_time_range(select: &Select, query: &Query, expr: &Expr) -> TimeRange {
    let f = match expr {
        Expr::Function(f) => f,
        _ => unreachable!("extract_time_range called on non-function"),
    };
    let args = function_args(f);

    let time_col = args
        .first()
        .and_then(arg_as_expr)
        .map(extract_column)
        .unwrap_or_default();

    let fill_gaps = has_with_fill(query);
    let (from_val, to_val) = extract_time_bounds_from_select(select, &time_col);

    let mut interval_value = String::new();
    let mut interval_unit = String::new();
    if let Some(Expr::Function(interval_fn)) = args.get(1).and_then(arg_as_expr) {
        let interval_args = function_args(interval_fn);
        if interval_args.len() >= 2 {
            if let Some(e) = arg_as_expr(&interval_args[0]) {
                interval_value = normalize_value(e);
            }
            if let Some(e) = arg_as_expr(&interval_args[1]) {
                interval_unit = normalize_value(e);
            }
        }
    }

    TimeRange {
        column: time_col,
        from: from_val,
        to: to_val,
        interval_unit,
        interval_value,
        fill_gaps,
    }
}

fn arg_as_expr(arg: &FunctionArg) -> Option<&Expr> {
    match arg {
        FunctionArg::Unnamed(FunctionArgExpr::Expr(e)) => Some(e),
        FunctionArg::Named { arg, .. } | FunctionArg::ExprNamed { arg, .. } => match arg {
            FunctionArgExpr::Expr(e) => Some(e),
            _ => None,
        },
        _ => None,
    }
}

fn has_with_fill(query: &Query) -> bool {
    if let Some(order_by) = &query.order_by {
        if let OrderByKind::Expressions(exprs) = &order_by.kind {
            return exprs.iter().any(|e: &OrderByExpr| e.with_fill.is_some());
        }
    }
    false
}

fn normalize_type(type_str: &str) -> String {
    match type_str.to_uppercase().as_str() {
        "TEXT" => "String".to_string(),
        "DATETIME64" => "DateTime64".to_string(),
        "DATETIME" => "DateTime64".to_string(),
        _ => type_str.to_string(),
    }
}

/// Reconstruct a placeholder `{name:Type}` from a parsed Dictionary expr, or
/// render a literal value without quotes (matching the Python normalizer).
fn normalize_value(expr: &Expr) -> String {
    match expr {
        Expr::Dictionary(fields) if !fields.is_empty() => {
            let field = &fields[0];
            let name = field.key.value.clone();
            let kind = match field.value.as_ref() {
                Expr::Identifier(ident) => ident.value.clone(),
                other => other.to_string(),
            };
            format!("{{{}:{}}}", name, normalize_type(&kind))
        }
        Expr::Value(v) => match &v.value {
            Value::Number(n, _) => n.clone(),
            Value::SingleQuotedString(s) => s.clone(),
            other => other.to_string(),
        },
        other => other.to_string(),
    }
}

fn extract_time_bounds_from_select(select: &Select, time_col: &str) -> (String, String) {
    let mut from_val = DEFAULT_START_TIME.to_string();
    let mut to_val = DEFAULT_END_TIME.to_string();
    if let Some(selection) = &select.selection {
        walk_time_bounds(selection, time_col, &mut from_val, &mut to_val);
    }
    (from_val, to_val)
}

fn walk_time_bounds(expr: &Expr, time_col: &str, from_val: &mut String, to_val: &mut String) {
    if let Expr::BinaryOp { left, op, right } = expr {
        match op {
            BinaryOperator::And | BinaryOperator::Or => {
                walk_time_bounds(left, time_col, from_val, to_val);
                walk_time_bounds(right, time_col, from_val, to_val);
            }
            BinaryOperator::GtEq => {
                if column_name(left).as_deref() == Some(time_col) {
                    *from_val = normalize_value(right);
                }
            }
            BinaryOperator::LtEq => {
                if column_name(left).as_deref() == Some(time_col) {
                    *to_val = normalize_value(right);
                }
            }
            _ => {}
        }
    }
}

fn parse_where_clause(select: &Select, time_range: Option<&TimeRange>) -> Vec<Filter> {
    let Some(selection) = &select.selection else {
        return Vec::new();
    };
    let time_col = time_range.map(|t| t.column.clone());
    let mut filters = Vec::new();
    walk_filters(selection, time_col.as_deref(), &mut filters);
    filters
}

fn comparison_op(op: &BinaryOperator) -> Option<&'static str> {
    match op {
        BinaryOperator::Eq => Some("eq"),
        BinaryOperator::NotEq => Some("ne"),
        BinaryOperator::Gt => Some("gt"),
        BinaryOperator::GtEq => Some("gte"),
        BinaryOperator::Lt => Some("lt"),
        BinaryOperator::LtEq => Some("lte"),
        _ => None,
    }
}

/// Extract `(raw_value_string, is_placeholder)` from a comparison RHS.
fn extract_rhs_value(expr: &Expr) -> (String, bool) {
    match expr {
        Expr::Dictionary(_) => (normalize_value(expr), true),
        Expr::Value(v) => match &v.value {
            Value::Number(n, _) => (n.clone(), false),
            Value::SingleQuotedString(s) => (s.clone(), false),
            other => (other.to_string(), false),
        },
        other => (other.to_string(), false),
    }
}

fn walk_filters(expr: &Expr, time_col: Option<&str>, filters: &mut Vec<Filter>) {
    match expr {
        Expr::BinaryOp { left, op, right } => {
            if matches!(op, BinaryOperator::And | BinaryOperator::Or) {
                walk_filters(left, time_col, filters);
                walk_filters(right, time_col, filters);
                return;
            }
            if let Some(op_str) = comparison_op(op) {
                let Some(col) = column_name(left) else {
                    return;
                };
                if time_col == Some(col.as_str()) {
                    return;
                }
                let (val, is_placeholder) = extract_rhs_value(right);
                let value = if is_placeholder {
                    FilterValue::StringValue(val)
                } else if let Ok(n) = val.parse::<f64>() {
                    FilterValue::NumberValue(n)
                } else {
                    FilterValue::StringValue(val)
                };
                filters.push(Filter {
                    field: col,
                    op: op_str.to_string(),
                    value: Some(value),
                });
            }
        }
        Expr::Function(f) if function_name(f).to_lowercase() == "has" => {
            let args = function_args(f);
            if args.len() >= 2 {
                let col = arg_as_expr(&args[0]).map(extract_column);
                if let Some(col) = col {
                    if !col.is_empty() && time_col != Some(col.as_str()) {
                        let val = arg_as_expr(&args[1])
                            .map(normalize_value)
                            .unwrap_or_default();
                        filters.push(Filter {
                            field: col,
                            op: "includes".to_string(),
                            value: Some(FilterValue::StringValue(val)),
                        });
                    }
                }
            }
        }
        _ => {}
    }
}

fn parse_order_by_clause(query: &Query) -> Vec<OrderBy> {
    let Some(order_by) = &query.order_by else {
        return Vec::new();
    };
    let OrderByKind::Expressions(exprs) = &order_by.kind else {
        return Vec::new();
    };

    exprs
        .iter()
        .map(|o| {
            let field = match &o.expr {
                Expr::Identifier(ident) => ident.value.clone(),
                Expr::CompoundIdentifier(parts) => {
                    parts.last().map(|p| p.value.clone()).unwrap_or_default()
                }
                other => other.to_string(),
            };
            let dir = if o.options.asc == Some(false) {
                "desc"
            } else {
                "asc"
            };
            OrderBy {
                field,
                dir: dir.to_string(),
            }
        })
        .collect()
}

fn parse_limit_clause(query: &Query) -> Option<i32> {
    let limit_clause = query.limit_clause.as_ref()?;
    let limit_expr = match limit_clause {
        LimitClause::LimitOffset { limit, .. } => limit.as_ref()?,
        LimitClause::OffsetCommaLimit { limit, .. } => limit,
    };
    match limit_expr {
        Expr::Value(v) => match &v.value {
            Value::Number(n, _) => n.parse::<i32>().ok(),
            _ => None,
        },
        other => other.to_string().parse::<i32>().ok(),
    }
}

#[cfg(test)]
mod tests;
