--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: subscription_tiers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription_tiers (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    pipeline_runs_per_month bigint NOT NULL,
    storage_mib bigint NOT NULL,
    log_retention_days bigint NOT NULL,
    members_per_workspace bigint DEFAULT '-1'::bigint NOT NULL,
    num_workspaces bigint DEFAULT '-1'::bigint NOT NULL,
    projects_per_workspace bigint DEFAULT '1'::bigint NOT NULL,
    stripe_product_id text DEFAULT ''::text NOT NULL,
    pipeline_pulls_per_month bigint DEFAULT '-1'::bigint NOT NULL
);


ALTER TABLE public.subscription_tiers OWNER TO postgres;

--
-- Name: COLUMN subscription_tiers.storage_mib; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.subscription_tiers.storage_mib IS 'Storage space allocated in MibiBytes (1024 x 1024 bytes)';


--
-- Name: subscription_tiers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription_tiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_tiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_tiers subscription_tiers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription_tiers
    ADD CONSTRAINT subscription_tiers_pkey PRIMARY KEY (id);


--
-- Name: subscription_tiers; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription_tiers ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE subscription_tiers; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.subscription_tiers TO anon;
GRANT ALL ON TABLE public.subscription_tiers TO authenticated;
GRANT ALL ON TABLE public.subscription_tiers TO service_role;


--
-- Name: SEQUENCE subscription_tiers_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.subscription_tiers_id_seq TO anon;
GRANT ALL ON SEQUENCE public.subscription_tiers_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.subscription_tiers_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

