// GENERATED — do not edit by hand (scratchpad/gen-icon-maps.cjs).
import {
  ActivityIcon,
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowDownIcon,
  ArrowLeft01Icon,
  ArrowLeftIcon,
  ArrowLeftRightIcon,
  ArrowRight01Icon,
  ArrowRightIcon,
  ArrowUp01Icon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  BoltIcon,
  BookIcon,
  BotIcon,
  BoxesIcon,
  BoxIcon,
  BracesIcon,
  BrainIcon,
  BugIcon,
  Calendar01Icon,
  CalendarIcon,
  Cancel01Icon,
  ChartAreaIcon,
  ChartColumnIcon,
  ChartLineIcon,
  ChartNoAxesGanttIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsRightIcon,
  CircleDashedIcon,
  CircleDollarSignIcon,
  CircleDotIcon,
  CircleIcon,
  CircleMinusIcon,
  CirclePlusIcon,
  Clock3Icon,
  ClockIcon,
  CloudIcon,
  CloudOffIcon,
  CoinsIcon,
  Copy01Icon,
  CopyIcon,
  CreditCardIcon,
  DatabaseIcon,
  DatabaseZapIcon,
  Delete02Icon,
  DollarSignIcon,
  Download01Icon,
  EditIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileCodeIcon,
  FileIcon,
  FilterIcon,
  FlagTriangleRightIcon,
  FlaskConicalIcon,
  FolderOpenIcon,
  FrownIcon,
  GaugeIcon,
  GitBranchIcon,
  GitForkIcon,
  GlobeIcon,
  GripHorizontalIcon,
  GripVerticalIcon,
  HashIcon,
  HelpCircleIcon,
  HistoryIcon,
  HomeIcon,
  ImageIcon,
  InboxIcon,
  KeyIcon,
  LayersIcon,
  LinkIcon,
  ListRestartIcon,
  ListTreeIcon,
  Loading01Icon,
  LockIcon,
  MailIcon,
  MaximizeIcon,
  MinimizeIcon,
  MinusSignIcon,
  MoreHorizontalIcon,
  Notification01Icon,
  PanelLeftIcon,
  PencilIcon,
  PenIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusSignIcon,
  RadioIcon,
  SaveIcon,
  Search01Icon,
  Settings01Icon,
  Settings02Icon,
  ShareIcon,
  ShieldIcon,
  SlackIcon,
  SlidersHorizontalIcon,
  SparklesIcon,
  SquareIcon,
  StarIcon,
  TagIcon,
  TagsIcon,
  TargetIcon,
  TerminalIcon,
  Tick01Icon,
  UploadIcon,
  UserGroupIcon,
  UserIcon,
  VariableIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons";

// lucide icon name -> hugeicons icon data object.
export const hugeiconsMap: Record<string, unknown> = {
  "Activity": ActivityIcon,
  "AlertCircle": AlertCircleIcon,
  "ArrowDown": ArrowDownIcon,
  "ArrowDownIcon": ArrowDownIcon,
  "ArrowLeft": ArrowLeftIcon,
  "ArrowLeftRight": ArrowLeftRightIcon,
  "ArrowRight": ArrowRightIcon,
  "ArrowUp": ArrowUpIcon,
  "ArrowUpLeft": ArrowUpLeftIcon,
  "ArrowUpRight": ArrowUpRightIcon,
  "Bell": Notification01Icon,
  "Bolt": BoltIcon,
  "Book": BookIcon,
  "Bot": BotIcon,
  "Box": BoxIcon,
  "Boxes": BoxesIcon,
  "Braces": BracesIcon,
  "BracesIcon": BracesIcon,
  "Brain": BrainIcon,
  "Bug": BugIcon,
  "Calendar": Calendar01Icon,
  "CalendarIcon": CalendarIcon,
  "ChartArea": ChartAreaIcon,
  "ChartColumn": ChartColumnIcon,
  "ChartLine": ChartLineIcon,
  "ChartNoAxesGantt": ChartNoAxesGanttIcon,
  "Check": Tick01Icon,
  "CheckIcon": CheckIcon,
  "ChevronDown": ArrowDown01Icon,
  "ChevronLeft": ArrowLeft01Icon,
  "ChevronLeftIcon": ChevronLeftIcon,
  "ChevronRight": ArrowRight01Icon,
  "ChevronRightIcon": ChevronRightIcon,
  "ChevronUp": ArrowUp01Icon,
  "ChevronsRight": ChevronsRightIcon,
  "Circle": CircleIcon,
  "CircleDashed": CircleDashedIcon,
  "CircleDollarSign": CircleDollarSignIcon,
  "CircleDot": CircleDotIcon,
  "CircleIcon": CircleIcon,
  "CircleMinus": CircleMinusIcon,
  "CirclePlus": CirclePlusIcon,
  "Clock": ClockIcon,
  "Clock3": Clock3Icon,
  "Cloud": CloudIcon,
  "CloudOff": CloudOffIcon,
  "Coins": CoinsIcon,
  "Copy": Copy01Icon,
  "CopyIcon": CopyIcon,
  "CreditCard": CreditCardIcon,
  "Database": DatabaseIcon,
  "DatabaseZap": DatabaseZapIcon,
  "DollarSign": DollarSignIcon,
  "Download": Download01Icon,
  "Edit": EditIcon,
  "Ellipsis": EllipsisIcon,
  "EllipsisVertical": EllipsisVerticalIcon,
  "ExternalLink": ExternalLinkIcon,
  "Eye": EyeIcon,
  "EyeOff": EyeOffIcon,
  "File": FileIcon,
  "FileCode": FileCodeIcon,
  "Filter": FilterIcon,
  "FlagTriangleRight": FlagTriangleRightIcon,
  "FlaskConical": FlaskConicalIcon,
  "FolderOpen": FolderOpenIcon,
  "Frown": FrownIcon,
  "Gauge": GaugeIcon,
  "GitBranch": GitBranchIcon,
  "GitFork": GitForkIcon,
  "Globe": GlobeIcon,
  "GripHorizontal": GripHorizontalIcon,
  "GripVertical": GripVerticalIcon,
  "GripVerticalIcon": GripVerticalIcon,
  "Hash": HashIcon,
  "HelpCircle": HelpCircleIcon,
  "History": HistoryIcon,
  "Home": HomeIcon,
  "Image": ImageIcon,
  "Inbox": InboxIcon,
  "Key": KeyIcon,
  "Layers": LayersIcon,
  "Link": LinkIcon,
  "ListRestart": ListRestartIcon,
  "ListTree": ListTreeIcon,
  "Loader2": Loading01Icon,
  "Lock": LockIcon,
  "Mail": MailIcon,
  "Maximize": MaximizeIcon,
  "Minimize": MinimizeIcon,
  "Minus": MinusSignIcon,
  "MoreHorizontal": MoreHorizontalIcon,
  "PanelLeft": PanelLeftIcon,
  "PanelLeftIcon": PanelLeftIcon,
  "Pen": PenIcon,
  "Pencil": PencilIcon,
  "PencilIcon": PencilIcon,
  "Play": PlayIcon,
  "PlayCircle": PlayCircleIcon,
  "PlayIcon": PlayIcon,
  "Plus": PlusSignIcon,
  "Radio": RadioIcon,
  "Save": SaveIcon,
  "Search": Search01Icon,
  "Settings": Settings01Icon,
  "Settings2": Settings02Icon,
  "Share": ShareIcon,
  "Shield": ShieldIcon,
  "Slack": SlackIcon,
  "SlidersHorizontal": SlidersHorizontalIcon,
  "Sparkles": SparklesIcon,
  "Square": SquareIcon,
  "Star": StarIcon,
  "Tag": TagIcon,
  "Tags": TagsIcon,
  "Target": TargetIcon,
  "Terminal": TerminalIcon,
  "Trash2": Delete02Icon,
  "Upload": UploadIcon,
  "User": UserIcon,
  "Users": UserGroupIcon,
  "VariableIcon": VariableIcon,
  "X": Cancel01Icon,
  "Zap": ZapIcon,
};
