// GENERATED by ./gen-icon-maps.cjs — do not edit by hand.
// Lucide icon name -> phosphor export (verified against the installed package; misses render a placeholder).
import { ArrowCounterClockwise } from "@phosphor-icons/react/ArrowCounterClockwise";
import { ArrowDown } from "@phosphor-icons/react/ArrowDown";
import { ArrowLeft } from "@phosphor-icons/react/ArrowLeft";
import { ArrowRight } from "@phosphor-icons/react/ArrowRight";
import { ArrowsClockwise } from "@phosphor-icons/react/ArrowsClockwise";
import { ArrowsIn } from "@phosphor-icons/react/ArrowsIn";
import { ArrowsLeftRight } from "@phosphor-icons/react/ArrowsLeftRight";
import { ArrowsOut } from "@phosphor-icons/react/ArrowsOut";
import { ArrowSquareOut } from "@phosphor-icons/react/ArrowSquareOut";
import { ArrowUp } from "@phosphor-icons/react/ArrowUp";
import { ArrowUpLeft } from "@phosphor-icons/react/ArrowUpLeft";
import { ArrowUpRight } from "@phosphor-icons/react/ArrowUpRight";
import { ArrowUUpLeft } from "@phosphor-icons/react/ArrowUUpLeft";
import { Bell } from "@phosphor-icons/react/Bell";
import { Book } from "@phosphor-icons/react/Book";
import { BracketsCurly } from "@phosphor-icons/react/BracketsCurly";
import { Brain } from "@phosphor-icons/react/Brain";
import { Bug } from "@phosphor-icons/react/Bug";
import { Calendar } from "@phosphor-icons/react/Calendar";
import { CaretDoubleRight } from "@phosphor-icons/react/CaretDoubleRight";
import { CaretDown } from "@phosphor-icons/react/CaretDown";
import { CaretLeft } from "@phosphor-icons/react/CaretLeft";
import { CaretRight } from "@phosphor-icons/react/CaretRight";
import { CaretUp } from "@phosphor-icons/react/CaretUp";
import { CaretUpDown } from "@phosphor-icons/react/CaretUpDown";
import { ChartBar } from "@phosphor-icons/react/ChartBar";
import { ChartLine } from "@phosphor-icons/react/ChartLine";
import { ChatCircle } from "@phosphor-icons/react/ChatCircle";
import { ChatCircleDots } from "@phosphor-icons/react/ChatCircleDots";
import { Check } from "@phosphor-icons/react/Check";
import { CheckCircle } from "@phosphor-icons/react/CheckCircle";
import { Circle } from "@phosphor-icons/react/Circle";
import { CircleDashed } from "@phosphor-icons/react/CircleDashed";
import { CircleNotch } from "@phosphor-icons/react/CircleNotch";
import { Clock } from "@phosphor-icons/react/Clock";
import { ClockCounterClockwise } from "@phosphor-icons/react/ClockCounterClockwise";
import { Cloud } from "@phosphor-icons/react/Cloud";
import { CloudSlash } from "@phosphor-icons/react/CloudSlash";
import { Code } from "@phosphor-icons/react/Code";
import { Coins } from "@phosphor-icons/react/Coins";
import { Columns } from "@phosphor-icons/react/Columns";
import { Copy } from "@phosphor-icons/react/Copy";
import { CreditCard } from "@phosphor-icons/react/CreditCard";
import { CurrencyDollar } from "@phosphor-icons/react/CurrencyDollar";
import { Database } from "@phosphor-icons/react/Database";
import { DotsSix } from "@phosphor-icons/react/DotsSix";
import { DotsSixVertical } from "@phosphor-icons/react/DotsSixVertical";
import { DotsThree } from "@phosphor-icons/react/DotsThree";
import { DotsThreeVertical } from "@phosphor-icons/react/DotsThreeVertical";
import { DownloadSimple } from "@phosphor-icons/react/DownloadSimple";
import { Envelope } from "@phosphor-icons/react/Envelope";
import { Equals } from "@phosphor-icons/react/Equals";
import { Eye } from "@phosphor-icons/react/Eye";
import { EyeSlash } from "@phosphor-icons/react/EyeSlash";
import { File } from "@phosphor-icons/react/File";
import { FileCode } from "@phosphor-icons/react/FileCode";
import { FilePlus } from "@phosphor-icons/react/FilePlus";
import { FileText } from "@phosphor-icons/react/FileText";
import { Flag } from "@phosphor-icons/react/Flag";
import { Flask } from "@phosphor-icons/react/Flask";
import { FloppyDisk } from "@phosphor-icons/react/FloppyDisk";
import { FlowArrow } from "@phosphor-icons/react/FlowArrow";
import { Folder } from "@phosphor-icons/react/Folder";
import { FolderOpen } from "@phosphor-icons/react/FolderOpen";
import { Function } from "@phosphor-icons/react/Function";
import { Funnel } from "@phosphor-icons/react/Funnel";
import { Gauge } from "@phosphor-icons/react/Gauge";
import { Gear } from "@phosphor-icons/react/Gear";
import { GearSix } from "@phosphor-icons/react/GearSix";
import { GitBranch } from "@phosphor-icons/react/GitBranch";
import { GitFork } from "@phosphor-icons/react/GitFork";
import { Globe } from "@phosphor-icons/react/Globe";
import { HardDrives } from "@phosphor-icons/react/HardDrives";
import { Hash } from "@phosphor-icons/react/Hash";
import { House } from "@phosphor-icons/react/House";
import { Image } from "@phosphor-icons/react/Image";
import { Info } from "@phosphor-icons/react/Info";
import { Key } from "@phosphor-icons/react/Key";
import { Layout } from "@phosphor-icons/react/Layout";
import { Lightning } from "@phosphor-icons/react/Lightning";
import { Link } from "@phosphor-icons/react/Link";
import { List } from "@phosphor-icons/react/List";
import { ListChecks } from "@phosphor-icons/react/ListChecks";
import { Lock } from "@phosphor-icons/react/Lock";
import { MagnifyingGlass } from "@phosphor-icons/react/MagnifyingGlass";
import { MagnifyingGlassMinus } from "@phosphor-icons/react/MagnifyingGlassMinus";
import { Minus } from "@phosphor-icons/react/Minus";
import { MinusCircle } from "@phosphor-icons/react/MinusCircle";
import { MonitorPlay } from "@phosphor-icons/react/MonitorPlay";
import { Package } from "@phosphor-icons/react/Package";
import { Palette } from "@phosphor-icons/react/Palette";
import { Paperclip } from "@phosphor-icons/react/Paperclip";
import { PaperPlaneTilt } from "@phosphor-icons/react/PaperPlaneTilt";
import { Pencil } from "@phosphor-icons/react/Pencil";
import { PencilSimple } from "@phosphor-icons/react/PencilSimple";
import { Person } from "@phosphor-icons/react/Person";
import { Play } from "@phosphor-icons/react/Play";
import { PlayCircle } from "@phosphor-icons/react/PlayCircle";
import { Plugs } from "@phosphor-icons/react/Plugs";
import { Plus } from "@phosphor-icons/react/Plus";
import { PlusCircle } from "@phosphor-icons/react/PlusCircle";
import { Pulse } from "@phosphor-icons/react/Pulse";
import { Question } from "@phosphor-icons/react/Question";
import { Radio } from "@phosphor-icons/react/Radio";
import { RadioButton } from "@phosphor-icons/react/RadioButton";
import { Robot } from "@phosphor-icons/react/Robot";
import { Rows } from "@phosphor-icons/react/Rows";
import { Share } from "@phosphor-icons/react/Share";
import { Shield } from "@phosphor-icons/react/Shield";
import { ShieldCheck } from "@phosphor-icons/react/ShieldCheck";
import { Sidebar } from "@phosphor-icons/react/Sidebar";
import { SidebarSimple } from "@phosphor-icons/react/SidebarSimple";
import { SignOut } from "@phosphor-icons/react/SignOut";
import { SlackLogo } from "@phosphor-icons/react/SlackLogo";
import { Sliders } from "@phosphor-icons/react/Sliders";
import { SmileySad } from "@phosphor-icons/react/SmileySad";
import { Sparkle } from "@phosphor-icons/react/Sparkle";
import { Square } from "@phosphor-icons/react/Square";
import { SquaresFour } from "@phosphor-icons/react/SquaresFour";
import { Stack } from "@phosphor-icons/react/Stack";
import { Star } from "@phosphor-icons/react/Star";
import { Table } from "@phosphor-icons/react/Table";
import { Tag } from "@phosphor-icons/react/Tag";
import { Target } from "@phosphor-icons/react/Target";
import { Terminal } from "@phosphor-icons/react/Terminal";
import { TerminalWindow } from "@phosphor-icons/react/TerminalWindow";
import { TextAlignJustify } from "@phosphor-icons/react/TextAlignJustify";
import { Trash } from "@phosphor-icons/react/Trash";
import { Tray } from "@phosphor-icons/react/Tray";
import { TreeStructure } from "@phosphor-icons/react/TreeStructure";
import { UploadSimple } from "@phosphor-icons/react/UploadSimple";
import { User } from "@phosphor-icons/react/User";
import { Users } from "@phosphor-icons/react/Users";
import { Warning } from "@phosphor-icons/react/Warning";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { X } from "@phosphor-icons/react/X";
import type React from "react";

export const phosphorMap: Record<string, React.ComponentType<Record<string, unknown>>> = {
  "Activity": Pulse,
  "AlertCircle": WarningCircle,
  "AlertTriangle": Warning,
  "AlignJustify": TextAlignJustify,
  "ArrowDown": ArrowDown,
  "ArrowDownIcon": ArrowDown,
  "ArrowLeft": ArrowLeft,
  "ArrowLeftRight": ArrowsLeftRight,
  "ArrowRight": ArrowRight,
  "ArrowUp": ArrowUp,
  "ArrowUpLeft": ArrowUpLeft,
  "ArrowUpRight": ArrowUpRight,
  "Bell": Bell,
  "Bolt": Lightning,
  "Book": Book,
  "Bot": Robot,
  "Box": Package,
  "Boxes": Stack,
  "Braces": BracketsCurly,
  "BracesIcon": BracketsCurly,
  "Brain": Brain,
  "Bug": Bug,
  "Calendar": Calendar,
  "CalendarIcon": Calendar,
  "ChartArea": ChartLine,
  "ChartBar": ChartBar,
  "ChartColumn": ChartBar,
  "ChartLine": ChartLine,
  "ChartNoAxesGantt": ChartBar,
  "Check": Check,
  "CheckCircle": CheckCircle,
  "CheckCircle2": CheckCircle,
  "CheckIcon": Check,
  "ChevronDown": CaretDown,
  "ChevronLeft": CaretLeft,
  "ChevronLeftIcon": CaretLeft,
  "ChevronRight": CaretRight,
  "ChevronRightIcon": CaretRight,
  "ChevronsRight": CaretDoubleRight,
  "ChevronsUpDown": CaretUpDown,
  "ChevronUp": CaretUp,
  "Circle": Circle,
  "CircleAlert": WarningCircle,
  "CircleDashed": CircleDashed,
  "CircleDollarSign": CurrencyDollar,
  "CircleDot": RadioButton,
  "CircleIcon": Circle,
  "CircleMinus": MinusCircle,
  "CirclePlay": PlayCircle,
  "CirclePlus": PlusCircle,
  "Clock": Clock,
  "Clock3": Clock,
  "Cloud": Cloud,
  "CloudOff": CloudSlash,
  "Code2": Code,
  "Coins": Coins,
  "Columns2": Columns,
  "Copy": Copy,
  "CopyIcon": Copy,
  "CreditCard": CreditCard,
  "Database": Database,
  "DatabaseZap": Database,
  "DollarSign": CurrencyDollar,
  "Download": DownloadSimple,
  "Edit": PencilSimple,
  "Ellipsis": DotsThree,
  "EllipsisVertical": DotsThreeVertical,
  "Equal": Equals,
  "ExternalLink": ArrowSquareOut,
  "Eye": Eye,
  "EyeOff": EyeSlash,
  "File": File,
  "FileBarChart": FileText,
  "FileCode": FileCode,
  "FileJson2": FileCode,
  "FilePlus2": FilePlus,
  "FileText": FileText,
  "Filter": Funnel,
  "FlagTriangleRight": Flag,
  "FlaskConical": Flask,
  "FolderClosed": Folder,
  "FolderOpen": FolderOpen,
  "Frown": SmileySad,
  "GanttChart": ChartBar,
  "Gauge": Gauge,
  "GitBranch": GitBranch,
  "GitFork": GitFork,
  "Globe": Globe,
  "GripHorizontal": DotsSix,
  "GripVertical": DotsSixVertical,
  "GripVerticalIcon": DotsSixVertical,
  "Hash": Hash,
  "HelpCircle": Question,
  "History": ClockCounterClockwise,
  "Home": House,
  "Image": Image,
  "ImagePlus": Image,
  "Inbox": Tray,
  "Info": Info,
  "Key": Key,
  "Layers": Stack,
  "Layers2": Stack,
  "LayoutDashboard": SquaresFour,
  "LayoutTemplate": Layout,
  "Link": Link,
  "List": List,
  "ListChecks": ListChecks,
  "ListFilter": Funnel,
  "ListRestart": List,
  "ListTree": TreeStructure,
  "Loader": CircleNotch,
  "Loader2": CircleNotch,
  "Lock": Lock,
  "LogOut": SignOut,
  "Mail": Envelope,
  "Maximize": ArrowsOut,
  "MessageCircle": ChatCircle,
  "MessageCirclePlus": ChatCircleDots,
  "Minimize": ArrowsIn,
  "Minus": Minus,
  "MonitorPlay": MonitorPlay,
  "MoreHorizontal": DotsThree,
  "Palette": Palette,
  "PanelLeft": SidebarSimple,
  "PanelLeftIcon": Sidebar,
  "Paperclip": Paperclip,
  "Pen": PencilSimple,
  "Pencil": PencilSimple,
  "PencilIcon": Pencil,
  "PersonStanding": Person,
  "Play": Play,
  "PlayCircle": PlayCircle,
  "PlayIcon": Play,
  "Plus": Plus,
  "Radio": Radio,
  "RefreshCw": ArrowsClockwise,
  "RotateCcw": ArrowCounterClockwise,
  "Rows2": Rows,
  "Rows4": Rows,
  "Save": FloppyDisk,
  "Search": MagnifyingGlass,
  "Send": PaperPlaneTilt,
  "Server": HardDrives,
  "Settings": Gear,
  "Settings2": GearSix,
  "Share": Share,
  "Shield": Shield,
  "ShieldCheck": ShieldCheck,
  "Slack": SlackLogo,
  "SlidersHorizontal": Sliders,
  "Sparkles": Sparkle,
  "Square": Square,
  "SquareArrowOutUpRight": ArrowSquareOut,
  "SquareFunction": Function,
  "SquareTerminal": TerminalWindow,
  "Star": Star,
  "Table2": Table,
  "TableProperties": Table,
  "Tag": Tag,
  "Tags": Tag,
  "Target": Target,
  "Terminal": Terminal,
  "TextSearch": MagnifyingGlass,
  "Trash": Trash,
  "Trash2": Trash,
  "TriangleAlert": Warning,
  "Undo2": ArrowUUpLeft,
  "Unplug": Plugs,
  "Upload": UploadSimple,
  "User": User,
  "Users": Users,
  "VariableIcon": Function,
  "Workflow": FlowArrow,
  "X": X,
  "Zap": Lightning,
  "ZoomOut": MagnifyingGlassMinus,
};
