// GENERATED — do not edit by hand (scratchpad/gen-icon-maps.cjs).
import {
  RiAddLine,
  RiAlertLine,
  RiArrowDownLine,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowLeftRightLine,
  RiArrowLeftSLine,
  RiArrowRightDoubleLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowUpLine,
  RiArrowUpSLine,
  RiBookLine,
  RiBracesLine,
  RiBrainLine,
  RiBugLine,
  RiCalendarLine,
  RiCheckLine,
  RiCircleLine,
  RiCloseLine,
  RiCloudLine,
  RiCloudOffLine,
  RiCoinsLine,
  RiDatabaseLine,
  RiDeleteBinLine,
  RiDownloadLine,
  RiEditLine,
  RiEqualLine,
  RiErrorWarningLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiEyeOffLine,
  RiFileCodeLine,
  RiFileCopyLine,
  RiFileLine,
  RiFileTextLine,
  RiFilterLine,
  RiFlashlightLine,
  RiFolderOpenLine,
  RiGitBranchLine,
  RiGitForkLine,
  RiGlobeLine,
  RiGroupLine,
  RiHistoryLine,
  RiHomeLine,
  RiImageLine,
  RiInboxLine,
  RiInformationLine,
  RiKeyLine,
  RiLoader4Line,
  RiLockLine,
  RiLogoutBoxLine,
  RiMailLine,
  RiMoreLine,
  RiNotification3Line,
  RiPaletteLine,
  RiPencilLine,
  RiPlayCircleLine,
  RiPlayLine,
  RiRadioLine,
  RiRefreshLine,
  RiSaveLine,
  RiSearchLine,
  RiSendPlaneLine,
  RiServerLine,
  RiSettings3Line,
  RiSettings4Line,
  RiShareLine,
  RiShieldCheckLine,
  RiShieldLine,
  RiSlackLine,
  RiSparkling2Line,
  RiSquareLine,
  RiStarLine,
  RiSubtractLine,
  RiTargetLine,
  RiTerminalLine,
  RiUploadLine,
  RiUserLine,
  RiZoomOutLine,
} from "@remixicon/react";
import type * as React from "react";

// lucide icon name -> remixMap component (only verified names; misses render a placeholder).
export const remixMap: Record<string, React.ComponentType<Record<string, unknown>>> = {
  "AlertCircle": RiErrorWarningLine,
  "AlertTriangle": RiAlertLine,
  "ArrowDown": RiArrowDownLine,
  "ArrowDownIcon": RiArrowDownLine,
  "ArrowLeft": RiArrowLeftLine,
  "ArrowLeftRight": RiArrowLeftRightLine,
  "ArrowRight": RiArrowRightLine,
  "ArrowUp": RiArrowUpLine,
  "Bell": RiNotification3Line,
  "Book": RiBookLine,
  "Braces": RiBracesLine,
  "BracesIcon": RiBracesLine,
  "Brain": RiBrainLine,
  "Bug": RiBugLine,
  "Calendar": RiCalendarLine,
  "CalendarIcon": RiCalendarLine,
  "Check": RiCheckLine,
  "CheckIcon": RiCheckLine,
  "ChevronDown": RiArrowDownSLine,
  "ChevronLeft": RiArrowLeftSLine,
  "ChevronRight": RiArrowRightSLine,
  "ChevronUp": RiArrowUpSLine,
  "ChevronsRight": RiArrowRightDoubleLine,
  "Circle": RiCircleLine,
  "CircleAlert": RiErrorWarningLine,
  "CircleIcon": RiCircleLine,
  "Cloud": RiCloudLine,
  "CloudOff": RiCloudOffLine,
  "Coins": RiCoinsLine,
  "Copy": RiFileCopyLine,
  "Database": RiDatabaseLine,
  "Download": RiDownloadLine,
  "Edit": RiEditLine,
  "Equal": RiEqualLine,
  "ExternalLink": RiExternalLinkLine,
  "Eye": RiEyeLine,
  "EyeOff": RiEyeOffLine,
  "File": RiFileLine,
  "FileCode": RiFileCodeLine,
  "FileText": RiFileTextLine,
  "Filter": RiFilterLine,
  "FolderOpen": RiFolderOpenLine,
  "GitBranch": RiGitBranchLine,
  "GitFork": RiGitForkLine,
  "Globe": RiGlobeLine,
  "History": RiHistoryLine,
  "Home": RiHomeLine,
  "Image": RiImageLine,
  "Inbox": RiInboxLine,
  "Info": RiInformationLine,
  "Key": RiKeyLine,
  "Loader": RiLoader4Line,
  "Loader2": RiLoader4Line,
  "Lock": RiLockLine,
  "LogOut": RiLogoutBoxLine,
  "Mail": RiMailLine,
  "Minus": RiSubtractLine,
  "MoreHorizontal": RiMoreLine,
  "Palette": RiPaletteLine,
  "Pen": RiEditLine,
  "Pencil": RiEditLine,
  "PencilIcon": RiPencilLine,
  "Play": RiPlayLine,
  "PlayCircle": RiPlayCircleLine,
  "PlayIcon": RiPlayLine,
  "Plus": RiAddLine,
  "Radio": RiRadioLine,
  "RefreshCw": RiRefreshLine,
  "Save": RiSaveLine,
  "Search": RiSearchLine,
  "Send": RiSendPlaneLine,
  "Server": RiServerLine,
  "Settings": RiSettings3Line,
  "Settings2": RiSettings4Line,
  "Share": RiShareLine,
  "Shield": RiShieldLine,
  "ShieldCheck": RiShieldCheckLine,
  "Slack": RiSlackLine,
  "Sparkles": RiSparkling2Line,
  "Square": RiSquareLine,
  "Star": RiStarLine,
  "Target": RiTargetLine,
  "Terminal": RiTerminalLine,
  "Trash": RiDeleteBinLine,
  "Trash2": RiDeleteBinLine,
  "Upload": RiUploadLine,
  "User": RiUserLine,
  "Users": RiGroupLine,
  "X": RiCloseLine,
  "Zap": RiFlashlightLine,
  "ZoomOut": RiZoomOutLine,
};
