// GENERATED — do not edit by hand (scratchpad/gen-icon-maps.cjs).
import {
  IconActivity,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowLeftRight,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpLeft,
  IconArrowUpRight,
  IconBell,
  IconBolt,
  IconBook,
  IconBox,
  IconBraces,
  IconBrain,
  IconBug,
  IconCalendar,
  IconChartArea,
  IconChartBar,
  IconChartColumn,
  IconChartLine,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsRight,
  IconChevronUp,
  IconCircle,
  IconCircleDashed,
  IconCircleDot,
  IconCircleMinus,
  IconCirclePlus,
  IconClock,
  IconCloud,
  IconCloudOff,
  IconCoins,
  IconColumns2,
  IconCopy,
  IconCreditCard,
  IconDatabase,
  IconDots,
  IconDownload,
  IconEqual,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileCode,
  IconFileText,
  IconFilter,
  IconFolderOpen,
  IconGauge,
  IconGitBranch,
  IconGitFork,
  IconGlobe,
  IconGripHorizontal,
  IconGripVertical,
  IconHash,
  IconHelpCircle,
  IconHistory,
  IconHome,
  IconInbox,
  IconKey,
  IconLayoutDashboard,
  IconLayoutSidebar,
  IconLink,
  IconList,
  IconListTree,
  IconLoader,
  IconLoader2,
  IconLock,
  IconLogout,
  IconMail,
  IconMaximize,
  IconMessageCircle,
  IconMessageCirclePlus,
  IconMinimize,
  IconMinus,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPlus,
  IconRadio,
  IconRefresh,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconSettings2,
  IconShare,
  IconShield,
  IconShieldCheck,
  IconSparkles,
  IconSquare,
  IconStar,
  IconTag,
  IconTags,
  IconTarget,
  IconTerminal,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconVariable,
  IconZoomOut,
} from "@tabler/icons-react";
import type * as React from "react";

// lucide icon name -> tablerMap component (only verified names; misses render a placeholder).
export const tablerMap: Record<string, React.ComponentType<Record<string, unknown>>> = {
  "Activity": IconActivity,
  "AlertCircle": IconAlertCircle,
  "AlertTriangle": IconAlertTriangle,
  "ArrowDown": IconArrowDown,
  "ArrowDownIcon": IconArrowDown,
  "ArrowLeft": IconArrowLeft,
  "ArrowLeftRight": IconArrowLeftRight,
  "ArrowRight": IconArrowRight,
  "ArrowUp": IconArrowUp,
  "ArrowUpLeft": IconArrowUpLeft,
  "ArrowUpRight": IconArrowUpRight,
  "Bell": IconBell,
  "Bolt": IconBolt,
  "Book": IconBook,
  "Box": IconBox,
  "Braces": IconBraces,
  "BracesIcon": IconBraces,
  "Brain": IconBrain,
  "Bug": IconBug,
  "Calendar": IconCalendar,
  "CalendarIcon": IconCalendar,
  "ChartArea": IconChartArea,
  "ChartBar": IconChartBar,
  "ChartColumn": IconChartColumn,
  "ChartLine": IconChartLine,
  "Check": IconCheck,
  "CheckIcon": IconCheck,
  "ChevronDown": IconChevronDown,
  "ChevronLeft": IconChevronLeft,
  "ChevronLeftIcon": IconChevronLeft,
  "ChevronRight": IconChevronRight,
  "ChevronRightIcon": IconChevronRight,
  "ChevronUp": IconChevronUp,
  "ChevronsRight": IconChevronsRight,
  "Circle": IconCircle,
  "CircleAlert": IconAlertCircle,
  "CircleDashed": IconCircleDashed,
  "CircleDot": IconCircleDot,
  "CircleIcon": IconCircle,
  "CircleMinus": IconCircleMinus,
  "CirclePlus": IconCirclePlus,
  "Clock": IconClock,
  "Cloud": IconCloud,
  "CloudOff": IconCloudOff,
  "Coins": IconCoins,
  "Columns2": IconColumns2,
  "Copy": IconCopy,
  "CopyIcon": IconCopy,
  "CreditCard": IconCreditCard,
  "Database": IconDatabase,
  "Download": IconDownload,
  "Edit": IconPencil,
  "Equal": IconEqual,
  "ExternalLink": IconExternalLink,
  "Eye": IconEye,
  "EyeOff": IconEyeOff,
  "File": IconFile,
  "FileCode": IconFileCode,
  "FileText": IconFileText,
  "Filter": IconFilter,
  "FolderOpen": IconFolderOpen,
  "Gauge": IconGauge,
  "GitBranch": IconGitBranch,
  "GitFork": IconGitFork,
  "Globe": IconGlobe,
  "GripHorizontal": IconGripHorizontal,
  "GripVertical": IconGripVertical,
  "GripVerticalIcon": IconGripVertical,
  "Hash": IconHash,
  "HelpCircle": IconHelpCircle,
  "History": IconHistory,
  "Home": IconHome,
  "Inbox": IconInbox,
  "Key": IconKey,
  "LayoutDashboard": IconLayoutDashboard,
  "Link": IconLink,
  "List": IconList,
  "ListTree": IconListTree,
  "Loader": IconLoader,
  "Loader2": IconLoader2,
  "Lock": IconLock,
  "LogOut": IconLogout,
  "Mail": IconMail,
  "Maximize": IconMaximize,
  "MessageCircle": IconMessageCircle,
  "MessageCirclePlus": IconMessageCirclePlus,
  "Minimize": IconMinimize,
  "Minus": IconMinus,
  "MoreHorizontal": IconDots,
  "Palette": IconPalette,
  "PanelLeft": IconLayoutSidebar,
  "Paperclip": IconPaperclip,
  "Pen": IconPencil,
  "Pencil": IconPencil,
  "PencilIcon": IconPencil,
  "Plus": IconPlus,
  "Radio": IconRadio,
  "RefreshCw": IconRefresh,
  "Search": IconSearch,
  "Send": IconSend,
  "Server": IconServer,
  "Settings": IconSettings,
  "Settings2": IconSettings2,
  "Share": IconShare,
  "Shield": IconShield,
  "ShieldCheck": IconShieldCheck,
  "Sparkles": IconSparkles,
  "Square": IconSquare,
  "Star": IconStar,
  "Tag": IconTag,
  "Tags": IconTags,
  "Target": IconTarget,
  "Terminal": IconTerminal,
  "Trash": IconTrash,
  "Trash2": IconTrash,
  "Upload": IconUpload,
  "User": IconUser,
  "Users": IconUsers,
  "VariableIcon": IconVariable,
  "ZoomOut": IconZoomOut,
};
