(() => {
  let context;
  let playback;
  const midiToFrequency = midi => 440 * 2 ** ((midi - 69) / 12);
  const clamp = (value, low, high) => Math.max(low, Math.min(high, value));

  const treatments = {
    'felt-piano': {melody:'piano',harmony:'piano',motion:'bass',master:.78,melodyGain:.82,harmonyGain:.42,motionGain:.22,brightness:.42,width:.48,reverb:.28},
    'digital-pings': {melody:'glass',harmony:'pad',motion:'glass',master:.7,melodyGain:.76,harmonyGain:.35,motionGain:.18,brightness:.7,width:.72,reverb:.48},
    'chamber-strings': {melody:'violin',harmony:'pad',motion:'bass',master:.68,melodyGain:.72,harmonyGain:.5,motionGain:.18,brightness:.38,width:.68,reverb:.5},
    'hybrid-score': {melody:'piano',harmony:'pad',motion:'glass',master:.76,melodyGain:.78,harmonyGain:.4,motionGain:.16,brightness:.48,width:.68,reverb:.4},
    'signal-bloom': {melody:'bloom',harmony:'pad',motion:'air',master:.68,melodyGain:.72,harmonyGain:.32,motionGain:.22,brightness:.62,width:.86,reverb:.68},
    'paper-pulse': {melody:'pluck',harmony:'pad',motion:'tap',master:.72,melodyGain:.7,harmonyGain:.26,motionGain:.26,brightness:.58,width:.56,reverb:.2},
  };

  function getContext(){context??=new AudioContext();if(context.state==='suspended')context.resume();return context}
  function noise(ctx,seconds){const buffer=ctx.createBuffer(1,Math.max(1,Math.ceil(ctx.sampleRate*seconds)),ctx.sampleRate),data=buffer.getChannelData(0);let low=0;for(let i=0;i<data.length;i++){low=low*.9+(Math.random()*2-1)*.1;data[i]=low*2.2}return buffer}
  function impulse(ctx,seconds=2.4){const buffer=ctx.createBuffer(2,Math.ceil(ctx.sampleRate*seconds),ctx.sampleRate);for(let channel=0;channel<2;channel++){const data=buffer.getChannelData(channel);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length)**2.5}return buffer}
  function output(ctx,destination,pan=0){const p=ctx.createStereoPanner();p.pan.value=clamp(pan,-1,1);p.connect(destination);return p}

  function oscillatorVoice(ctx,destination,pitch,at,length,velocity,type='sine',attack=.012,release=.7,pan=0){
    const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.value=midiToFrequency(pitch);const end=at+Math.max(.08,Math.min(length+release,3));gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,velocity),at+Math.min(attack,length*.3));gain.gain.exponentialRampToValueAtTime(.0001,end);osc.connect(gain).connect(output(ctx,destination,pan));osc.start(at);osc.stop(end+.03);playback.sources.push(osc)
  }
  function piano(ctx,destination,pitch,at,length,velocity,preset,pan=0){for(let h=1;h<=5;h++){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=midiToFrequency(pitch)*h*(1+h*h*.00028);const peak=velocity*.09*(.35+preset.brightness*.3)**(h-1)/Math.sqrt(h),end=at+Math.max(.2,Math.min(2.6,length+1));gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,peak),at+.012);gain.gain.exponentialRampToValueAtTime(.0001,end);osc.connect(gain).connect(output(ctx,destination,pan*preset.width));osc.start(at);osc.stop(end+.03);playback.sources.push(osc)}const hit=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();hit.buffer=noise(ctx,.035);filter.type='highpass';filter.frequency.value=1800+preset.brightness*2600;gain.gain.setValueAtTime(velocity*.018,at);gain.gain.exponentialRampToValueAtTime(.0001,at+.04);hit.connect(filter).connect(gain).connect(destination);hit.start(at);hit.stop(at+.05);playback.sources.push(hit)}
  function glass(ctx,destination,pitch,at,length,velocity,preset,pan=0){[1,2.01,3.98].forEach((ratio,index)=>oscillatorVoice(ctx,destination,pitch+12*Math.log2(ratio),at,length,velocity*.075/(index+1),index?'sine':'triangle',.006,.8-index*.16,pan*preset.width))}
  function violin(ctx,destination,pitch,at,length,velocity,preset,pan=0){const bus=ctx.createBiquadFilter();bus.type='lowpass';bus.frequency.value=1200+preset.brightness*2600;bus.connect(output(ctx,destination,pan*preset.width));oscillatorVoice(ctx,bus,pitch,at,length,velocity*.07,'sawtooth',.09,.18,0);oscillatorVoice(ctx,bus,pitch,at,length,velocity*.035,'triangle',.12,.2,0)}
  function pad(ctx,destination,notes,at,length,velocity,preset){notes.forEach((pitch,index)=>oscillatorVoice(ctx,destination,pitch,at,length,velocity*.035/Math.sqrt(notes.length),'triangle',Math.min(.22,length*.25),.05,(index-(notes.length-1)/2)*.13*preset.width))}
  function bass(ctx,destination,pitch,at,length,velocity){oscillatorVoice(ctx,destination,pitch,at,Math.min(length,1.1),velocity*.07,'triangle',.025,.12,-.08)}
  function bloom(ctx,destination,pitch,at,length,velocity,preset,pan=0){const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(700,at);filter.frequency.exponentialRampToValueAtTime(2600,at+Math.min(length,.65));filter.connect(output(ctx,destination,pan*preset.width));oscillatorVoice(ctx,filter,pitch,at,Math.max(length,.7),velocity*.055,'sine',.16,1.2,0);oscillatorVoice(ctx,filter,pitch+12,at+.06,Math.max(length,.6),velocity*.018,'sine',.2,1.1,0)}
  function pluck(ctx,destination,pitch,at,length,velocity,preset,pan=0){const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1000+preset.brightness*2800;filter.Q.value=2.8;filter.connect(output(ctx,destination,pan*preset.width));oscillatorVoice(ctx,filter,pitch,at,Math.min(length,.45),velocity*.095,'triangle',.004,.16,0)}
  function air(ctx,destination,pitch,at,length,velocity){const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=noise(ctx,Math.min(.7,length+.2));filter.type='bandpass';filter.frequency.value=midiToFrequency(pitch);filter.Q.value=5;gain.gain.setValueAtTime(.0001,at);gain.gain.linearRampToValueAtTime(velocity*.06,at+.12);gain.gain.exponentialRampToValueAtTime(.0001,at+Math.min(.65,length+.15));source.connect(filter).connect(gain).connect(destination);source.start(at);source.stop(at+Math.min(.75,length+.25));playback.sources.push(source)}
  function tap(ctx,destination,pitch,at,velocity){const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=noise(ctx,.04);filter.type='bandpass';filter.frequency.value=midiToFrequency(pitch);filter.Q.value=7;gain.gain.setValueAtTime(velocity*.11,at);gain.gain.exponentialRampToValueAtTime(.0001,at+.045);source.connect(filter).connect(gain).connect(destination);source.start(at);source.stop(at+.05);playback.sources.push(source)}

  function makeGraph(ctx,preset,mode){const master=ctx.createGain(),compressor=ctx.createDynamicsCompressor(),dry=ctx.createGain(),convolver=ctx.createConvolver(),wet=ctx.createGain();master.gain.value=preset.master;compressor.threshold.value=-18;compressor.ratio.value=3;convolver.buffer=impulse(ctx);dry.gain.value=1-preset.reverb*.25;wet.gain.value=preset.reverb*.5;dry.connect(master);convolver.connect(wet).connect(master);master.connect(compressor).connect(ctx.destination);const buses={};for(const [name,base] of Object.entries({melody:preset.melodyGain,harmony:preset.harmonyGain,motion:preset.motionGain})){const gain=ctx.createGain();gain.gain.value=base*(mode==='underscore'&&name==='harmony'?1.05:1);gain.connect(dry);gain.connect(convolver);buses[name]=gain}return{master,buses}}
  function voice(instrument,ctx,bus,pitch,at,length,velocity,preset,pan=0){if(instrument==='piano')piano(ctx,bus,pitch,at,length,velocity,preset,pan);else if(instrument==='glass')glass(ctx,bus,pitch,at,length,velocity,preset,pan);else if(instrument==='violin')violin(ctx,bus,pitch,at,length,velocity,preset,pan);else if(instrument==='bloom')bloom(ctx,bus,pitch,at,length,velocity,preset,pan);else pluck(ctx,bus,pitch,at,length,velocity,preset,pan)}
  function bounds(song,mode,dna){const total=song.melody.reduce((sum,item)=>sum+item.beats,0);if(mode==='dna'){const first=dna.occurrences[0];return{start:first.at,end:first.at+first.beats,total}}if(mode==='ending')return{start:Math.max(0,total-8),end:total,total};return{start:0,end:total,total}}
  function inDna(beat,dna){return dna.occurrences.some(item=>beat>=item.at&&beat<item.at+item.beats)}

  function schedule(song,treatmentId,mode,dna,fromBeat=0){
    stop();const ctx=getContext(),preset=treatments[treatmentId]??treatments['hybrid-score'],graph=makeGraph(ctx,preset,mode),secondsPerBeat=60/song.tempo,range=bounds(song,mode,dna),startBeat=clamp(fromBeat,range.start,range.end),start=ctx.currentTime+.06;
    playback={ctx,graph,sources:[],start,fromBeat:startBeat,startBeat:range.start,endBeat:range.end,secondsPerBeat};
    const scheduleAt=(beat,duration,callback)=>{const eventEnd=Math.min(beat+duration,range.end);if(eventEnd<=startBeat||beat>=range.end)return;const clipped=Math.max(beat,startBeat),at=start+(clipped-startBeat)*secondsPerBeat,length=Math.max(.06,(eventEnd-clipped)*secondsPerBeat);callback(at,length)};
    let beat=0;
    if(mode!=='ending')song.melody.forEach((item,index)=>{const eventBeat=beat;beat+=item.beats;if(item.pitch===null)return;if(mode==='underscore'&&!inDna(eventBeat,dna))return;scheduleAt(eventBeat,item.beats,(at,length)=>voice(preset.melody,ctx,graph.buses.melody,item.pitch,at,length,(mode==='underscore'?.48:.72)*(index%4===0?1:.9),preset,((index%7)-3)/12))});
    beat=0;song.chords.forEach((item,index)=>{const eventBeat=beat;beat+=item.beats;scheduleAt(eventBeat,item.beats,(at,length)=>{pad(ctx,graph.buses.harmony,item.notes,at,length,mode==='underscore'?.48:.68,preset);if(mode==='full'&&index%2===1){const pitch=preset.motion==='bass'?item.notes[0]-12:item.notes[index%item.notes.length]+12;if(preset.motion==='bass')bass(ctx,graph.buses.motion,pitch,at,length,.5);else if(preset.motion==='air')air(ctx,graph.buses.motion,pitch,at,length,.4);else if(preset.motion==='tap')tap(ctx,graph.buses.motion,pitch,at,.4);else glass(ctx,graph.buses.motion,pitch,at,.2,.32,preset,index%4===1?.35:-.35)}})});
    if(mode==='ending'){const cadenceStart=range.end-8,cadenceTotal=song.cadence.reduce((sum,item)=>sum+item.beats,0);let cadenceBeat=cadenceStart;song.cadence.forEach((item,index)=>{const duration=item.beats/cadenceTotal*8;scheduleAt(cadenceBeat,duration,(at,length)=>voice(preset.melody,ctx,graph.buses.melody,item.pitch,at,length,index===song.cadence.length-1?.9:.65,preset,0));cadenceBeat+=duration});const tonic=song.chords.at(-1)?.notes??[48,52,55];scheduleAt(cadenceStart,8,(at,length)=>pad(ctx,graph.buses.harmony,tonic,at,length,.62,preset))}
    return state();
  }
  function stop(){if(!playback)return;for(const source of playback.sources)try{source.stop()}catch{}playback.graph.master.gain.setTargetAtTime(.0001,playback.ctx.currentTime,.012);playback=null}
  function state(){if(!playback)return null;const beat=playback.fromBeat+Math.max(0,playback.ctx.currentTime-playback.start)/playback.secondsPerBeat;return{beat,start:playback.startBeat,end:playback.endBeat,ended:beat>=playback.endBeat,playing:true}}
  window.SongStudioEngine={play:schedule,stop,state,midiToFrequency};
})();
