pub mod client;
pub mod utils;

pub use client::GeminiClient;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// https://ai.google.dev/gemini-api/docs/troubleshooting#error-codes

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GeminiErrorStatus {
    InvalidArgument,
    FailedPrecondition,
    PermissionDenied,
    NotFound,
    ResourceExhausted,
    Internal,
    Unavailable,
    DeadlineExceeded,
    Unknown(String),
}

impl GeminiErrorStatus {
    pub fn is_retryable(&self) -> bool {
        matches!(
            self,
            GeminiErrorStatus::Internal
                | GeminiErrorStatus::Unavailable
                | GeminiErrorStatus::DeadlineExceeded
        )
    }

    pub fn from_http(status_code: u16, status_msg: &str) -> Self {
        match (status_code, status_msg) {
            (400, msg) if msg.contains("INVALID_ARGUMENT") => Self::InvalidArgument,
            (400, msg) if msg.contains("FAILED_PRECONDITION") => Self::FailedPrecondition,
            (403, _) => Self::PermissionDenied,
            (404, _) => Self::NotFound,
            (429, _) => Self::ResourceExhausted,
            (500, _) => Self::Internal,
            (503, _) => Self::Unavailable,
            (504, _) => Self::DeadlineExceeded,
            _ => Self::Unknown(status_msg.to_string()),
        }
    }
}

#[derive(Debug, Error)]
pub enum GeminiError {
    #[error("Request failed: {0}")]
    RequestError(#[from] reqwest::Error),

    #[error("Failed to parse response: {0}")]
    ParseError(#[from] serde_json::Error),

    #[error("Configuration error: {0}")]
    ConfigError(String),

    #[error("Gemini API error ({status_code} {status:?}): {message}")]
    ApiError {
        status_code: u16,
        status: GeminiErrorStatus,
        message: String,
    },
}

impl GeminiError {
    pub fn config<S: Into<String>>(msg: S) -> Self {
        GeminiError::ConfigError(msg.into())
    }

    pub fn from_response(status_code: u16, message: String) -> Self {
        let status = GeminiErrorStatus::from_http(status_code, &message);
        GeminiError::ApiError {
            status_code,
            status,
            message,
        }
    }

    pub fn is_retryable(&self) -> bool {
        match self {
            GeminiError::ApiError { status, .. } => status.is_retryable(),
            GeminiError::RequestError(_) => true,
            _ => false,
        }
    }
}

//https://ai.google.dev/api/batch-api

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Content {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parts: Option<Vec<Part>>,
}

/// A part of a multi-part content message.
/// See: https://ai.google.dev/api/caching#Part
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Part {
    // Data union - exactly one of these should be set
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inline_data: Option<Blob>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function_call: Option<FunctionCall>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function_response: Option<FunctionResponse>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_data: Option<FileData>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executable_code: Option<ExecutableCode>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code_execution_result: Option<CodeExecutionResult>,

    // Thought-related fields
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thought: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thought_signature: Option<String>,

    // Metadata fields
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub video_metadata: Option<VideoMetadata>,
}

/// Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Blob {
    /// The IANA standard MIME type of the source data.
    pub mime_type: String,
    /// Raw bytes for media formats. Base64-encoded string.
    pub data: String,
}

/// URI based data.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileData {
    /// The IANA standard MIME type of the source data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// URI of the file.
    pub file_uri: String,
}

/// Code generated by the model that is meant to be executed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecutableCode {
    /// Programming language of the code.
    pub language: Language,
    /// The code to be executed.
    pub code: String,
}

/// Supported programming languages for ExecutableCode.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Language {
    LanguageUnspecified,
    Python,
}

/// Result of executing the ExecutableCode.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodeExecutionResult {
    /// Outcome of the code execution.
    pub outcome: Outcome,
    /// Contains stdout when code execution is successful, stderr or other description otherwise.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
}

/// Enumeration of possible outcomes of the code execution.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Outcome {
    OutcomeUnspecified,
    OutcomeOk,
    OutcomeFailed,
    OutcomeDeadlineExceeded,
}

/// Metadata describes the input video content.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoMetadata {
    /// Optional. The start offset of the video.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_offset: Option<Duration>,
    /// Optional. The end offset of the video.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_offset: Option<Duration>,
}

/// A Duration represents a signed, fixed-length span of time.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Duration {
    /// Signed seconds of the span of time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i64>,
    /// Signed fractions of a second at nanosecond resolution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nanos: Option<i32>,
}

/// A predicted FunctionCall returned from the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionCall {
    /// Optional. The unique id of the function call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Required. The name of the function to call.
    pub name: String,
    /// Optional. The function parameters and values in JSON object format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<serde_json::Value>,
}

/// The result output from a FunctionCall.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FunctionResponse {
    /// Optional. The id of the function call this response is for.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Required. The name of the function to call.
    pub name: String,
    /// Required. The function response in JSON object format.
    pub response: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct GenerationConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_k: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_sequences: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionDeclaration {
    pub name: String,
    pub description: String,
    pub parameters: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tool {
    pub function_declarations: Vec<FunctionDeclaration>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateContentRequest {
    pub contents: Vec<Content>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generation_config: Option<GenerationConfig>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_instruction: Option<Content>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InlineRequests {
    pub requests: Vec<InlineRequestItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InlineRequestItem {
    pub request: GenerateContentRequest,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InputConfig {
    pub requests: Option<InlineRequests>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Batch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    pub input_config: InputConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchCreateRequest {
    pub batch: Batch,
}

impl BatchCreateRequest {
    pub fn inline(requests: Vec<InlineRequestItem>, display_name: Option<String>) -> Self {
        Self {
            batch: Batch {
                display_name,
                input_config: InputConfig {
                    requests: Some(InlineRequests { requests }),
                    file_name: None,
                },
            },
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub enum JobState {
    BATCH_STATE_UNSPECIFIED,
    BATCH_STATE_PENDING,
    BATCH_STATE_RUNNING,
    BATCH_STATE_SUCCEEDED,
    BATCH_STATE_FAILED,
    BATCH_STATE_CANCELLED,
    BATCH_STATE_EXPIRED,
}

impl JobState {
    pub fn should_retry_failed(&self) -> bool {
        match self {
            JobState::BATCH_STATE_FAILED
            | JobState::BATCH_STATE_EXPIRED
            | JobState::BATCH_STATE_UNSPECIFIED => true,
            JobState::BATCH_STATE_CANCELLED => false,
            _ => false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchStats {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_count: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pending_request_count: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub successful_request_count: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed_request_count: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InlinedResponsesWrapper {
    pub inlined_responses: Vec<InlineResponse>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateContentBatchOutput {
    pub inlined_responses: InlinedResponsesWrapper,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorInfo {
    pub code: i32,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<serde_json::Value>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchJobMetadata {
    #[serde(rename = "@type")]
    pub type_url: String,
    pub model: String,
    pub display_name: String,
    pub name: String,
    pub state: JobState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_stats: Option<BatchStats>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<GenerateContentBatchOutput>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Operation {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<BatchJobMetadata>,
    #[serde(default)]
    pub done: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorInfo>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<GenerateContentBatchOutput>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Candidate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<Content>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finish_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub safety_ratings: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UsageMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_token_count: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub candidates_token_count: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_token_count: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thoughts_token_count: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<Vec<serde_json::Value>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateContentResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub candidates: Option<Vec<Candidate>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_metadata: Option<UsageMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InlineResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<GenerateContentResponse>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorInfo>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}
