// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metric {
    #[prost(enumeration = "AggregationFunction", tag = "1")]
    pub r#fn: i32,
    #[prost(string, tag = "2")]
    pub column: ::prost::alloc::string::String,
    #[prost(double, repeated, tag = "3")]
    pub args: ::prost::alloc::vec::Vec<f64>,
    #[prost(string, tag = "4")]
    pub alias: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Filter {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(enumeration = "ComparisonOperator", tag = "2")]
    pub op: i32,
    #[prost(oneof = "filter::Value", tags = "3, 4")]
    pub value: ::core::option::Option<filter::Value>,
}
/// Nested message and enum types in `Filter`.
pub mod filter {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(double, tag = "4")]
        NumberValue(f64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeRange {
    #[prost(string, tag = "1")]
    pub column: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub interval_unit: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub interval_value: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub fill_gaps: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBy {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderDirection", tag = "2")]
    pub dir: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryStructure {
    #[prost(string, tag = "1")]
    pub table: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub metrics: ::prost::alloc::vec::Vec<Metric>,
    #[prost(string, repeated, tag = "3")]
    pub dimensions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
    #[prost(message, optional, tag = "5")]
    pub time_range: ::core::option::Option<TimeRange>,
    #[prost(message, repeated, tag = "6")]
    pub order_by: ::prost::alloc::vec::Vec<OrderBy>,
    #[prost(int32, tag = "7")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryResponse {
    #[prost(oneof = "query_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<query_response::Result>,
}
/// Nested message and enum types in `QueryResponse`.
pub mod query_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SuccessResponse),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SuccessResponse {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorResponse {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JsonToSqlRequest {
    #[prost(message, optional, tag = "1")]
    pub query_structure: ::core::option::Option<QueryStructure>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JsonToSqlSuccessResponse {
    #[prost(string, tag = "1")]
    pub sql: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JsonToSqlResponse {
    #[prost(oneof = "json_to_sql_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<json_to_sql_response::Result>,
}
/// Nested message and enum types in `JsonToSqlResponse`.
pub mod json_to_sql_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::JsonToSqlSuccessResponse),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SqlToJsonRequest {
    #[prost(string, tag = "1")]
    pub sql: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SqlToJsonSuccessResponse {
    #[prost(message, optional, tag = "1")]
    pub query_structure: ::core::option::Option<QueryStructure>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SqlToJsonResponse {
    #[prost(oneof = "sql_to_json_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<sql_to_json_response::Result>,
}
/// Nested message and enum types in `SqlToJsonResponse`.
pub mod sql_to_json_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SqlToJsonSuccessResponse),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ComparisonOperator {
    Unspecified = 0,
    Eq = 1,
    Ne = 2,
    Gt = 3,
    Gte = 4,
    Lt = 5,
    Lte = 6,
}
impl ComparisonOperator {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMPARISON_OPERATOR_UNSPECIFIED",
            Self::Eq => "EQ",
            Self::Ne => "NE",
            Self::Gt => "GT",
            Self::Gte => "GTE",
            Self::Lt => "LT",
            Self::Lte => "LTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPARISON_OPERATOR_UNSPECIFIED" => Some(Self::Unspecified),
            "EQ" => Some(Self::Eq),
            "NE" => Some(Self::Ne),
            "GT" => Some(Self::Gt),
            "GTE" => Some(Self::Gte),
            "LT" => Some(Self::Lt),
            "LTE" => Some(Self::Lte),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AggregationFunction {
    Unspecified = 0,
    Count = 1,
    Sum = 2,
    Avg = 3,
    Min = 4,
    Max = 5,
    Quantile = 6,
}
impl AggregationFunction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGGREGATION_FUNCTION_UNSPECIFIED",
            Self::Count => "COUNT",
            Self::Sum => "SUM",
            Self::Avg => "AVG",
            Self::Min => "MIN",
            Self::Max => "MAX",
            Self::Quantile => "QUANTILE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGGREGATION_FUNCTION_UNSPECIFIED" => Some(Self::Unspecified),
            "COUNT" => Some(Self::Count),
            "SUM" => Some(Self::Sum),
            "AVG" => Some(Self::Avg),
            "MIN" => Some(Self::Min),
            "MAX" => Some(Self::Max),
            "QUANTILE" => Some(Self::Quantile),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderDirection {
    Unspecified = 0,
    Asc = 1,
    Desc = 2,
}
impl OrderDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORDER_DIRECTION_UNSPECIFIED",
            Self::Asc => "ASC",
            Self::Desc => "DESC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "ASC" => Some(Self::Asc),
            "DESC" => Some(Self::Desc),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod query_engine_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct QueryEngineServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl QueryEngineServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryEngineServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryEngineServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QueryEngineServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn validate_query(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/query_engine.QueryEngineService/ValidateQuery",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("query_engine.QueryEngineService", "ValidateQuery"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn json_to_sql(
            &mut self,
            request: impl tonic::IntoRequest<super::JsonToSqlRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JsonToSqlResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/query_engine.QueryEngineService/JsonToSql",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("query_engine.QueryEngineService", "JsonToSql"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn sql_to_json(
            &mut self,
            request: impl tonic::IntoRequest<super::SqlToJsonRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SqlToJsonResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/query_engine.QueryEngineService/SqlToJson",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("query_engine.QueryEngineService", "SqlToJson"));
            self.inner.unary(req, path, codec).await
        }
    }
}
