#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# Fix for blank screen issue
export XKL_XMODMAP_DISABLE=1

vncconfig -iconic &
autocutsel -fork &

# Start desktop environment
startxfce4 &