# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12query_engine.proto\x12\x0cquery_engine\"1\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"y\n\rQueryResponse\x12\x30\n\x07success\x18\x01 \x01(\x0b\x32\x1d.query_engine.SuccessResponseH\x00\x12,\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1b.query_engine.ErrorResponseH\x00\x42\x08\n\x06result\" \n\x0fSuccessResponse\x12\r\n\x05query\x18\x01 \x01(\t\"\x1e\n\rErrorResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t2^\n\x12QueryEngineService\x12H\n\rValidateQuery\x12\x1a.query_engine.QueryRequest\x1a\x1b.query_engine.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=36
  _globals['_QUERYREQUEST']._serialized_end=85
  _globals['_QUERYRESPONSE']._serialized_start=87
  _globals['_QUERYRESPONSE']._serialized_end=208
  _globals['_SUCCESSRESPONSE']._serialized_start=210
  _globals['_SUCCESSRESPONSE']._serialized_end=242
  _globals['_ERRORRESPONSE']._serialized_start=244
  _globals['_ERRORRESPONSE']._serialized_end=274
  _globals['_QUERYENGINESERVICE']._serialized_start=276
  _globals['_QUERYENGINESERVICE']._serialized_end=370
# @@protoc_insertion_point(module_scope)
