# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import query_engine_pb2 as query__engine__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in query_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateQuery = channel.unary_unary(
                '/query_engine.QueryEngineService/ValidateQuery',
                request_serializer=query__engine__pb2.QueryRequest.SerializeToString,
                response_deserializer=query__engine__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.JsonToSql = channel.unary_unary(
                '/query_engine.QueryEngineService/JsonToSql',
                request_serializer=query__engine__pb2.JsonToSqlRequest.SerializeToString,
                response_deserializer=query__engine__pb2.JsonToSqlResponse.FromString,
                _registered_method=True)
        self.SqlToJson = channel.unary_unary(
                '/query_engine.QueryEngineService/SqlToJson',
                request_serializer=query__engine__pb2.SqlToJsonRequest.SerializeToString,
                response_deserializer=query__engine__pb2.SqlToJsonResponse.FromString,
                _registered_method=True)


class QueryEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JsonToSql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SqlToJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateQuery,
                    request_deserializer=query__engine__pb2.QueryRequest.FromString,
                    response_serializer=query__engine__pb2.QueryResponse.SerializeToString,
            ),
            'JsonToSql': grpc.unary_unary_rpc_method_handler(
                    servicer.JsonToSql,
                    request_deserializer=query__engine__pb2.JsonToSqlRequest.FromString,
                    response_serializer=query__engine__pb2.JsonToSqlResponse.SerializeToString,
            ),
            'SqlToJson': grpc.unary_unary_rpc_method_handler(
                    servicer.SqlToJson,
                    request_deserializer=query__engine__pb2.SqlToJsonRequest.FromString,
                    response_serializer=query__engine__pb2.SqlToJsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'query_engine.QueryEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('query_engine.QueryEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query_engine.QueryEngineService/ValidateQuery',
            query__engine__pb2.QueryRequest.SerializeToString,
            query__engine__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JsonToSql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query_engine.QueryEngineService/JsonToSql',
            query__engine__pb2.JsonToSqlRequest.SerializeToString,
            query__engine__pb2.JsonToSqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SqlToJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query_engine.QueryEngineService/SqlToJson',
            query__engine__pb2.SqlToJsonRequest.SerializeToString,
            query__engine__pb2.SqlToJsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
