// The one public Laminar trace every landing mock renders: an assistant asked
// "What is Laminar?" that searches, searches again, opens a docs page that
// 404s, searches a third time, and answers from a snippet without citing it.
// Those three failures are what the signal-event card describes.
//
//   ai.streamText
//   ├─ ai.llm    "let me search for this"          → web_search "Laminar"
//   ├─ ai.llm    "mostly fluid dynamics, narrow it" → web_search "Laminar agent observability"
//   ├─ ai.llm    "the docs page looks authoritative"→ fetch_page  ← 404, never retried
//   ├─ ai.llm    "search once more instead"         → web_search "Laminar open source"
//   └─ ai.llm    the answer, citing nothing
//
// Generated by `frontend/scripts/landing-trace`, which prints all ten span ids
// on every run. Only the five below are referenced anywhere, so they are the
// only ones kept here — regenerate, then update this file and nothing else.
//
// Read through the `/api/landing-traces` rewrite (see ./understand-why-trace-view
// /shared-trace-api), so the trace must be marked PUBLIC on laminar.sh or every
// panel renders empty.
//
// FLAG: sharing is a session-authed PUT that a project API key cannot make, so
// the script cannot do it — after regenerating, open the trace on laminar.sh
// and hit Share, then confirm
// `curl -sI https://laminar.sh/api/shared/traces/<id>` returns 200.
export const DEMO_TRACE_ID = "ca52e397-9212-d63b-f3bc-e50a642c39f2";

/** The agent deciding to search — the first reasoning the reader sees. */
export const DEMO_FIRST_LLM_SPAN_ID = "00000000-0000-0000-4fbc-89974ceb3411";
/** The first `web_search`. */
export const DEMO_FIRST_SEARCH_SPAN_ID = "00000000-0000-0000-fe13-e7eec4068533";
/** The `fetch_page` that 404s. The only span in the trace with `status: error`. */
export const DEMO_FAILED_FETCH_SPAN_ID = "00000000-0000-0000-9c87-1ab67fe62d56";
/** The third `web_search`, returning the same results as the second. */
export const DEMO_LAST_SEARCH_SPAN_ID = "00000000-0000-0000-bcef-5ab905e7ddee";
/** The answer, citing nothing. */
export const DEMO_ANSWER_SPAN_ID = "00000000-0000-0000-e644-64eda55faef9";
