// The one public Laminar trace every landing mock renders: a short assistant
// run — "What is Laminar?" → reason → web_search → answer.
//
// Generated by `frontend/scripts/landing-trace`. Regenerate there and update
// all five ids together; nothing else in the landing tree hardcodes a span id,
// so this file is the only thing a new trace invalidates.
//
// Read through the `/api/landing-traces` rewrite (see ./understand-why-trace-view
// /shared-trace-api), so the trace must be marked PUBLIC on laminar.sh or every
// panel renders empty.
export const DEMO_TRACE_ID = "f6593456-83c6-3c42-12dd-74cea3f22265";

export const DEMO_ROOT_SPAN_ID = "00000000-0000-0000-89fe-bcc254c352ea";
/** The agent deciding to search. */
export const DEMO_LLM1_SPAN_ID = "00000000-0000-0000-326f-ab066d5d9bf9";
export const DEMO_TOOL_SPAN_ID = "00000000-0000-0000-53b2-a2fe8f8931d8";
/** The agent answering from the search result. */
export const DEMO_LLM2_SPAN_ID = "00000000-0000-0000-f49a-ac51b74e2398";
