"use client";

/* GENERATED by scratchpad/gen-icon-maps.cjs — do not edit by hand.
 * TEMPORARY icon-library prototyping wrapper. Drop-in for "lucide-react".
 *   - "lucide" (default): native lucide-react icon (pixel-perfect)
 *   - tabler/phosphor/remix/hugeicons: the real package, via hand-verified per-library maps
 *     (./maps/*). An icon with no mapping for the active library renders a dashed placeholder.
 * Global default stroke width comes from ./store (per-call strokeWidth prop wins).
 */

import { HugeiconsIcon } from "@hugeicons/react";
import type { LucideIcon, LucideProps } from "lucide-react";
import * as Lucide from "lucide-react";
import * as React from "react";

import { hugeiconsMap } from "./maps/hugeicons";
import { phosphorMap } from "./maps/phosphor";
import { remixMap } from "./maps/remix";
import { tablerMap } from "./maps/tabler";
import { useIconLib, useIconStroke } from "./store";

// Safety net for any lucide export not explicitly wrapped (types, missed icons).
export * from "lucide-react";

type AnyComp = React.ComponentType<Record<string, unknown>>;

// Phosphor has no stroke width — approximate it with the nearest weight.
function strokeToWeight(w: number): "thin" | "light" | "regular" | "bold" {
  if (w <= 1) return "thin";
  if (w < 1.75) return "light";
  if (w < 2.5) return "regular";
  return "bold";
}

function Placeholder({ size }: { size: number | string }) {
  const s = typeof size === "number" ? `${size}px` : size;
  return (
    <span
      aria-hidden
      title="no mapping in this icon set"
      style={{ width: s, height: s, display: "inline-block" }}
      className="shrink-0 rounded-[2px] border border-dashed border-muted-foreground/40"
    />
  );
}

function makeIcon(lucideName: string): LucideIcon {
  const Comp = React.forwardRef<SVGSVGElement, LucideProps>(function WrappedIcon(
    { size = 24, strokeWidth, absoluteStrokeWidth, className, color, ...rest },
    ref
  ) {
    const lib = useIconLib();
    const globalStroke = useIconStroke();
    const stroke = typeof strokeWidth === "number" ? strokeWidth : globalStroke;

    if (lib === "lucide") {
      const L = (Lucide as unknown as Record<string, LucideIcon>)[lucideName];
      if (!L) return <Placeholder size={size} />;
      return (
        <L ref={ref} size={size} strokeWidth={stroke} absoluteStrokeWidth={absoluteStrokeWidth} className={className} color={color} {...rest} />
      );
    }
    if (lib === "tabler") {
      const C = tablerMap[lucideName] as AnyComp | undefined;
      return C ? <C size={size} stroke={stroke} className={className} color={color} {...rest} /> : <Placeholder size={size} />;
    }
    if (lib === "phosphor") {
      const C = phosphorMap[lucideName] as AnyComp | undefined;
      return C ? <C size={size} weight={strokeToWeight(stroke)} className={className} color={color} {...rest} /> : <Placeholder size={size} />;
    }
    if (lib === "remix") {
      const C = remixMap[lucideName] as AnyComp | undefined;
      return C ? <C size={size} className={className} color={color} {...rest} /> : <Placeholder size={size} />;
    }
    // hugeicons
    const obj = hugeiconsMap[lucideName];
    return obj ? (
      <HugeiconsIcon icon={obj as never} size={size} strokeWidth={stroke} className={className} color={color} {...(rest as object)} />
    ) : (
      <Placeholder size={size} />
    );
  });
  Comp.displayName = lucideName;
  return Comp as unknown as LucideIcon;
}

export const Activity = makeIcon("Activity");
export const AlertCircle = makeIcon("AlertCircle");
export const AlertTriangle = makeIcon("AlertTriangle");
export const AlignJustify = makeIcon("AlignJustify");
export const ArrowDown = makeIcon("ArrowDown");
export const ArrowDownIcon = makeIcon("ArrowDownIcon");
export const ArrowLeft = makeIcon("ArrowLeft");
export const ArrowLeftRight = makeIcon("ArrowLeftRight");
export const ArrowRight = makeIcon("ArrowRight");
export const ArrowUp = makeIcon("ArrowUp");
export const ArrowUpLeft = makeIcon("ArrowUpLeft");
export const ArrowUpRight = makeIcon("ArrowUpRight");
export const Bell = makeIcon("Bell");
export const Bolt = makeIcon("Bolt");
export const Book = makeIcon("Book");
export const Bot = makeIcon("Bot");
export const Box = makeIcon("Box");
export const Boxes = makeIcon("Boxes");
export const Braces = makeIcon("Braces");
export const BracesIcon = makeIcon("BracesIcon");
export const Brain = makeIcon("Brain");
export const Bug = makeIcon("Bug");
export const Calendar = makeIcon("Calendar");
export const CalendarIcon = makeIcon("CalendarIcon");
export const ChartArea = makeIcon("ChartArea");
export const ChartBar = makeIcon("ChartBar");
export const ChartColumn = makeIcon("ChartColumn");
export const ChartLine = makeIcon("ChartLine");
export const ChartNoAxesGantt = makeIcon("ChartNoAxesGantt");
export const Check = makeIcon("Check");
export const CheckCircle = makeIcon("CheckCircle");
export const CheckCircle2 = makeIcon("CheckCircle2");
export const CheckIcon = makeIcon("CheckIcon");
export const ChevronDown = makeIcon("ChevronDown");
export const ChevronLeft = makeIcon("ChevronLeft");
export const ChevronLeftIcon = makeIcon("ChevronLeftIcon");
export const ChevronRight = makeIcon("ChevronRight");
export const ChevronRightIcon = makeIcon("ChevronRightIcon");
export const ChevronUp = makeIcon("ChevronUp");
export const ChevronsRight = makeIcon("ChevronsRight");
export const ChevronsUpDown = makeIcon("ChevronsUpDown");
export const Circle = makeIcon("Circle");
export const CircleAlert = makeIcon("CircleAlert");
export const CircleDashed = makeIcon("CircleDashed");
export const CircleDollarSign = makeIcon("CircleDollarSign");
export const CircleDot = makeIcon("CircleDot");
export const CircleIcon = makeIcon("CircleIcon");
export const CircleMinus = makeIcon("CircleMinus");
export const CirclePlay = makeIcon("CirclePlay");
export const CirclePlus = makeIcon("CirclePlus");
export const Clock = makeIcon("Clock");
export const Clock3 = makeIcon("Clock3");
export const Cloud = makeIcon("Cloud");
export const CloudOff = makeIcon("CloudOff");
export const Code2 = makeIcon("Code2");
export const Coins = makeIcon("Coins");
export const Columns2 = makeIcon("Columns2");
export const Copy = makeIcon("Copy");
export const CopyIcon = makeIcon("CopyIcon");
export const CreditCard = makeIcon("CreditCard");
export const Database = makeIcon("Database");
export const DatabaseZap = makeIcon("DatabaseZap");
export const DollarSign = makeIcon("DollarSign");
export const Download = makeIcon("Download");
export const Edit = makeIcon("Edit");
export const Ellipsis = makeIcon("Ellipsis");
export const EllipsisVertical = makeIcon("EllipsisVertical");
export const Equal = makeIcon("Equal");
export const ExternalLink = makeIcon("ExternalLink");
export const Eye = makeIcon("Eye");
export const EyeOff = makeIcon("EyeOff");
export const File = makeIcon("File");
export const FileBarChart = makeIcon("FileBarChart");
export const FileCode = makeIcon("FileCode");
export const FileJson2 = makeIcon("FileJson2");
export const FilePlus2 = makeIcon("FilePlus2");
export const FileText = makeIcon("FileText");
export const Filter = makeIcon("Filter");
export const FlagTriangleRight = makeIcon("FlagTriangleRight");
export const FlaskConical = makeIcon("FlaskConical");
export const FolderClosed = makeIcon("FolderClosed");
export const FolderOpen = makeIcon("FolderOpen");
export const Frown = makeIcon("Frown");
export const GanttChart = makeIcon("GanttChart");
export const Gauge = makeIcon("Gauge");
export const GitBranch = makeIcon("GitBranch");
export const GitFork = makeIcon("GitFork");
export const Globe = makeIcon("Globe");
export const GripHorizontal = makeIcon("GripHorizontal");
export const GripVertical = makeIcon("GripVertical");
export const GripVerticalIcon = makeIcon("GripVerticalIcon");
export const Hash = makeIcon("Hash");
export const HelpCircle = makeIcon("HelpCircle");
export const History = makeIcon("History");
export const Home = makeIcon("Home");
export const Image = makeIcon("Image");
export const ImagePlus = makeIcon("ImagePlus");
export const Inbox = makeIcon("Inbox");
export const Info = makeIcon("Info");
export const Key = makeIcon("Key");
export const Layers = makeIcon("Layers");
export const Layers2 = makeIcon("Layers2");
export const LayoutDashboard = makeIcon("LayoutDashboard");
export const LayoutTemplate = makeIcon("LayoutTemplate");
export const Link = makeIcon("Link");
export const List = makeIcon("List");
export const ListChecks = makeIcon("ListChecks");
export const ListFilter = makeIcon("ListFilter");
export const ListRestart = makeIcon("ListRestart");
export const ListTree = makeIcon("ListTree");
export const Loader = makeIcon("Loader");
export const Loader2 = makeIcon("Loader2");
export const Lock = makeIcon("Lock");
export const LogOut = makeIcon("LogOut");
export const Mail = makeIcon("Mail");
export const Maximize = makeIcon("Maximize");
export const MessageCircle = makeIcon("MessageCircle");
export const MessageCirclePlus = makeIcon("MessageCirclePlus");
export const Minimize = makeIcon("Minimize");
export const Minus = makeIcon("Minus");
export const MonitorPlay = makeIcon("MonitorPlay");
export const MoreHorizontal = makeIcon("MoreHorizontal");
export const Palette = makeIcon("Palette");
export const PanelLeft = makeIcon("PanelLeft");
export const PanelLeftIcon = makeIcon("PanelLeftIcon");
export const Paperclip = makeIcon("Paperclip");
export const Pen = makeIcon("Pen");
export const Pencil = makeIcon("Pencil");
export const PencilIcon = makeIcon("PencilIcon");
export const PersonStanding = makeIcon("PersonStanding");
export const Play = makeIcon("Play");
export const PlayCircle = makeIcon("PlayCircle");
export const PlayIcon = makeIcon("PlayIcon");
export const Plus = makeIcon("Plus");
export const Radio = makeIcon("Radio");
export const RefreshCw = makeIcon("RefreshCw");
export const RotateCcw = makeIcon("RotateCcw");
export const Rows2 = makeIcon("Rows2");
export const Rows4 = makeIcon("Rows4");
export const Save = makeIcon("Save");
export const Search = makeIcon("Search");
export const Send = makeIcon("Send");
export const Server = makeIcon("Server");
export const Settings = makeIcon("Settings");
export const Settings2 = makeIcon("Settings2");
export const Share = makeIcon("Share");
export const Shield = makeIcon("Shield");
export const ShieldCheck = makeIcon("ShieldCheck");
export const Slack = makeIcon("Slack");
export const SlidersHorizontal = makeIcon("SlidersHorizontal");
export const Sparkles = makeIcon("Sparkles");
export const Square = makeIcon("Square");
export const SquareArrowOutUpRight = makeIcon("SquareArrowOutUpRight");
export const SquareFunction = makeIcon("SquareFunction");
export const SquareTerminal = makeIcon("SquareTerminal");
export const Star = makeIcon("Star");
export const Table2 = makeIcon("Table2");
export const TableProperties = makeIcon("TableProperties");
export const Tag = makeIcon("Tag");
export const Tags = makeIcon("Tags");
export const Target = makeIcon("Target");
export const Terminal = makeIcon("Terminal");
export const TextSearch = makeIcon("TextSearch");
export const Trash = makeIcon("Trash");
export const Trash2 = makeIcon("Trash2");
export const TriangleAlert = makeIcon("TriangleAlert");
export const Undo2 = makeIcon("Undo2");
export const Unplug = makeIcon("Unplug");
export const Upload = makeIcon("Upload");
export const User = makeIcon("User");
export const Users = makeIcon("Users");
export const VariableIcon = makeIcon("VariableIcon");
export const Workflow = makeIcon("Workflow");
export const X = makeIcon("X");
export const Zap = makeIcon("Zap");
export const ZoomOut = makeIcon("ZoomOut");
