// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RedactRequest {
    /// Each entry must be a stringified JSON value (object, array, or scalar).
    /// The service walks the tree, recursively parses string leaves whose
    /// content is itself stringified JSON, detects PII in string values, and
    /// returns each entry re-serialized as a compact JSON string together
    /// with the byte ranges to mask. Object keys are never masked;
    /// numbers/bools/null are passed through.
    #[prost(string, repeated, tag = "1")]
    pub texts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Object-key names whose VALUES should be skipped during detection
    /// (treated as structural metadata, not content). Applied at every nesting
    /// level. If empty, a built-in default list is used.
    #[prost(string, repeated, tag = "3")]
    pub skip_keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// One PII entity: byte offsets into `RedactedText.text` (start inclusive,
/// end exclusive, always on UTF-8 char boundaries) and the model's base label
/// (e.g. `private_email`).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mask {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, tag = "2")]
    pub end: u32,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactedText {
    /// Canonical compact re-serialization of the input, unredacted. Masks are
    /// offsets into exactly this string; store it verbatim if masks are kept.
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// Sorted, non-overlapping.
    #[prost(message, repeated, tag = "2")]
    pub masks: ::prost::alloc::vec::Vec<Mask>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedactResponse {
    /// One entry per request text, same order.
    #[prost(message, repeated, tag = "2")]
    pub results: ::prost::alloc::vec::Vec<RedactedText>,
}
/// Generated client implementations.
pub mod pii_redactor_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PiiRedactorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PiiRedactorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PiiRedactorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PiiRedactorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PiiRedactorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn redact(
            &mut self,
            request: impl tonic::IntoRequest<super::RedactRequest>,
        ) -> std::result::Result<tonic::Response<super::RedactResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pii_redactor.PiiRedactorService/Redact",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pii_redactor.PiiRedactorService", "Redact"));
            self.inner.unary(req, path, codec).await
        }
    }
}
