-- CREATE TABLE "table_views" (
-- 	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
-- 	"project_id" uuid NOT NULL,
-- 	"resource" text NOT NULL,
-- 	"name" text NOT NULL,
-- 	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
-- 	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
-- );
-- --> statement-breakpoint
-- ALTER TABLE "table_views" ADD CONSTRAINT "table_views_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- CREATE UNIQUE INDEX "table_views_project_id_resource_name_idx" ON "table_views" USING btree ("project_id" uuid_ops,"resource" text_ops,"name" text_ops);