name: Check Query Engine Tests

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - 'query-engine/**' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install the project
        working-directory: ./query-engine
        run: uv sync --all-extras --dev
      - name: Run tests
        working-directory: ./query-engine
        run: uv run pytest
