/**
 * UNREVIEWED COUNSEL DRAFT — NOT LEGAL ADVICE, NOT CLEARED FOR PUBLICATION.
 *
 * Drafted from a code-level data inventory (LAM-2028). Every factual claim here
 * traces to an inventory row; items that could not be determined from the code
 * are marked "not yet determined" rather than guessed. Open questions and
 * out-of-scope items are tracked in docs/internal/counsel-handoff.md.
 */
import { type Metadata } from "next";

import { withBasePath } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Privacy Notice - Laminar",
  description: "How Laminar handles personal data it controls and Customer Data it processes for customers.",
};

const LAST_UPDATED = "July 28, 2026";

export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto p-6 space-y-4">
      <h1>PRIVACY NOTICE</h1>
      <div>
        <strong>Last updated {LAST_UPDATED}</strong>
      </div>

      <p>
        This Privacy Notice explains how LMNR AI, Inc. (doing business as Laminar) (&quot;<strong>Laminar</strong>
        ,&quot; &quot;<strong>we</strong>,&quot; &quot;<strong>us</strong>,&quot; &quot;<strong>our</strong>&quot;)
        handles personal data in connection with the Laminar platform, our websites, our documentation, our SDKs and
        command-line tools, and our sales and marketing activities (together, the &quot;<strong>Services</strong>
        &quot;).
      </p>

      <p>
        Laminar is an observability platform for AI agents. Customers instrument their own applications with our SDKs,
        and those applications send us traces: structured records of what an agent did, including the prompts and
        completions exchanged with language models, tool calls, evaluation runs, and optionally browser session
        recordings. That content is generated by our customers&apos; systems and their end users, not by us.
      </p>

      <h2>How this notice is organised</h2>

      <p>
        Laminar handles two categories of data in two different legal capacities, and conflating them makes this notice
        impossible to read accurately. So this notice is split:
      </p>

      <ul>
        <li>
          <strong>
            <a href="#part-a">Part A — personal data Laminar controls.</a>
          </strong>{" "}
          Data about the people who deal with Laminar directly: account holders and their colleagues, prospects and
          people who contact us, billing contacts, and visitors to our websites and product. For this data Laminar is
          the <strong>controller</strong> (or, under US state privacy laws, the &quot;business&quot;). Part A is where
          your own individual privacy rights against Laminar live.
        </li>
        <li>
          <strong>
            <a href="#part-b">Part B — Customer Data Laminar processes on behalf of customers.</a>
          </strong>{" "}
          The traces, spans, language-model messages, session recordings, evaluation data and datasets that a customer
          sends to the platform. For this data Laminar is a <strong>processor</strong> (a &quot;service provider&quot;),
          acting on the customer&apos;s instructions under our Data Processing Addendum. The customer decides what to
          send us and why.
        </li>
      </ul>

      <p>
        <strong>If you are an end user of a product built by one of our customers</strong> and your data may be inside
        that customer&apos;s traces, Laminar is not your point of contact. Direct your access, correction and deletion
        requests to the company whose product you used; they are the controller and we act on their instructions. See{" "}
        <a href="#b-data-subjects">Part B, End-user data subjects</a>.
      </p>

      <p>
        Our approach to using Customer Data to improve our own models, and the Privacy Mode control that governs it, is
        summarised in plain English at <a href={withBasePath("/policies/data-use")}>Data use</a>. That page is a
        summary; Part B of this notice and the Data Processing Addendum are the operative terms.
      </p>

      <p>
        <strong>Questions.</strong> Contact us at <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a>, or by post at
        LMNR AI, Inc., 2261 Market Street, STE 10826, San Francisco, CA 94114, United States.
      </p>

      <h2>Self-hosted and single-tenant deployments</h2>

      <p>
        Laminar is open source and can be self-hosted. If you run Laminar on your own infrastructure, we do not receive
        your traces at all, and Part B of this notice does not describe your deployment — you are the operator of that
        installation. Self-hosted installations do send us an anonymous usage heartbeat, which is described in{" "}
        <a href="#a-telemetry">Part A, Self-hosted telemetry</a> and can be switched off.
      </p>

      <p>
        Customers on a hybrid or single-tenant data-plane deployment keep trace storage in their own environment.
        Customer Data in those deployments is never part of any Laminar training corpus. See{" "}
        <a href="#b-training">Part B, Model improvement</a>.
      </p>

      {/* ------------------------------------------------------------------ */}

      <h2 id="part-a">PART A — PERSONAL DATA LAMINAR CONTROLS</h2>

      <p>
        This Part covers personal data about identifiable individuals who interact with Laminar directly. It does not
        cover the contents of customer traces; those are addressed in Part B.
      </p>

      <h3 id="a-categories">A.1 What we collect</h3>

      <p>
        <strong>Account and profile data.</strong> Name, email address, and (where you sign in through an identity
        provider) profile picture URL. We record whether an email address has been verified. Stored in our primary
        database.
      </p>

      <p>
        <strong>Authentication data.</strong> Session records including session token, expiry, and — for each session —
        the <strong>IP address and user-agent string</strong> of the device that created it. Where you sign in through
        an identity provider, we store the provider account identifier and the OAuth tokens that provider issues to us.
        Where a deployment uses local email sign-in or password credentials, the corresponding credential record. We
        also store the signing keys used to issue platform tokens, and short-lived device-authorization codes used by
        our command-line tool.
      </p>

      <p>
        <strong>API credentials.</strong> Project API keys, including a hash of the key, a display shorthand, the
        identifier of the user who created the key, and any expiry you set. Keys are used to authenticate trace
        ingestion.
      </p>

      <p>
        <strong>Workspace and membership data.</strong> Workspace names, your role in each workspace, and pending
        invitations (including the invited email address).
      </p>

      <p>
        <strong>Billing data.</strong> For paid plans we store a Stripe customer identifier, the plan and any add-ons,
        and metered usage counters (bytes ingested, signal run counts and token-derived cost) per workspace and billing
        period. <strong>We do not store card numbers or other payment instrument data.</strong> Payment details are
        collected and held by Stripe as a separate controller for that processing; see{" "}
        <a href="https://stripe.com/privacy" target="_blank" rel="noreferrer">
          Stripe&apos;s privacy policy
        </a>
        . Billing is only present on Laminar Cloud.
      </p>

      <p>
        <strong>Support and sales data.</strong> The content of emails and messages you send us, and information you
        give us in demos, trials, and procurement or security review.
      </p>

      <p>
        <strong>Website and product analytics.</strong> When analytics is enabled on our hosted service we collect
        product usage events through PostHog — which feature you used and when, page views, and a workspace association
        — plus the technical data any web request carries (IP address, user agent, referrer). Our analytics identifier
        for a signed-in user is <strong>your email address</strong>. Session replay is enabled on our own web app with
        input masking configured (all form inputs masked and text content masked). Analytics is not enabled on
        self-hosted installations unless the operator turns it on.
      </p>

      <p>
        <strong>Error and performance monitoring.</strong> On Laminar Cloud we use Sentry to collect error reports,
        stack traces and performance traces from our frontend and backend. Server-side error reports are configured to
        include request-identifying information. An error report can incidentally contain fragments of whatever data the
        failing request was handling.
      </p>

      <p id="a-telemetry">
        <strong>Self-hosted telemetry.</strong> Self-hosted installations report an anonymous heartbeat to us roughly
        every six hours: an opaque per-installation identifier generated locally, the Laminar version, the environment
        label, which features are enabled, and row counts per data table. It carries no personal data, no customer
        content, and no IP address — the source IP is explicitly dropped and geolocation lookup is disabled. Operators
        can disable it by setting <code>LAMINAR_TELEMETRY_DISABLED=true</code>, and it is off on Laminar Cloud.
      </p>

      <p>
        <strong>Sensitive personal data.</strong> We do not ask for, and have no product need for, special-category or
        sensitive personal data in Part A. Note that the position is different for Customer Data — see{" "}
        <a href="#b-sensitive">Part B, Sensitive and special-category data</a>.
      </p>

      <h3 id="a-sources">A.2 Where it comes from</h3>

      <p>We obtain Part A personal data:</p>

      <ul>
        <li>from you, when you register, configure a workspace, contact us, or buy a plan;</li>
        <li>automatically, from your browser and our servers, when you use our websites and product;</li>
        <li>
          from your identity provider (GitHub, Google, Microsoft Entra ID, Okta or Keycloak, depending on how you sign
          in), which passes us your name, email address and profile picture;
        </li>
        <li>
          from a colleague, when they invite you to a workspace — in which case we hold your email address before you
          have had any contact with us; and
        </li>
        <li>from Stripe, in the form of subscription and payment status for your workspace.</li>
      </ul>

      <h3 id="a-purposes">A.3 Why we process it, and on what legal basis</h3>

      <p>
        Where the GDPR or UK GDPR applies, we rely on the legal bases set out below. Where a US state privacy law
        applies, the same purposes apply and consent is not generally required, subject to the opt-out rights in{" "}
        <a href="#a-us">A.7</a>.
      </p>

      <table>
        <thead>
          <tr>
            <th>Purpose</th>
            <th>Data used</th>
            <th>Legal basis (GDPR / UK GDPR)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Create and authenticate accounts; manage workspaces, roles and invitations</td>
            <td>Account, authentication, workspace and membership data</td>
            <td>Performance of a contract (Art. 6(1)(b))</td>
          </tr>
          <tr>
            <td>Operate, secure and support the platform; authenticate trace ingestion; enforce plan limits</td>
            <td>Account, API credential, usage counter data</td>
            <td>Performance of a contract (Art. 6(1)(b)); legitimate interests in platform security (Art. 6(1)(f))</td>
          </tr>
          <tr>
            <td>Take payment, invoice, and meter usage</td>
            <td>Billing data</td>
            <td>Performance of a contract (Art. 6(1)(b)); legal obligation for tax and accounting (Art. 6(1)(c))</td>
          </tr>
          <tr>
            <td>Send service and administrative notices, including usage and billing alerts</td>
            <td>Account and billing data</td>
            <td>Performance of a contract (Art. 6(1)(b))</td>
          </tr>
          <tr>
            <td>Respond to support requests and sales enquiries</td>
            <td>Support and sales data</td>
            <td>Performance of a contract (Art. 6(1)(b)); legitimate interests (Art. 6(1)(f))</td>
          </tr>
          <tr>
            <td>Understand product usage to improve the product; diagnose faults</td>
            <td>Analytics, error monitoring and telemetry data</td>
            <td>
              Legitimate interests in maintaining and improving the Services (Art. 6(1)(f)); consent where required for
              non-essential cookies and similar technologies (Art. 6(1)(a))
            </td>
          </tr>
          <tr>
            <td>Send marketing communications and manage our marketing audience</td>
            <td>Name, email address, signup date</td>
            <td>Consent (Art. 6(1)(a)), or legitimate interests for business-to-business marketing where permitted</td>
          </tr>
          <tr>
            <td>Comply with law; establish, exercise and defend legal claims; prevent fraud and abuse</td>
            <td>Any of the above, as strictly necessary</td>
            <td>Legal obligation (Art. 6(1)(c)); legitimate interests (Art. 6(1)(f))</td>
          </tr>
        </tbody>
      </table>

      <p>
        <strong>We do not use Part A personal data to train models.</strong> Model training is addressed exclusively in{" "}
        <a href="#b-training">Part B</a> and concerns Customer Data only.
      </p>

      <p>
        We do not sell Part A personal data, and we do not use it for cross-context behavioural advertising or for
        automated decision-making that produces legal or similarly significant effects.
      </p>

      <h3 id="a-recipients">A.4 Who we share it with</h3>

      <p>
        We disclose Part A personal data to the service providers below, each under a written contract that limits them
        to processing it for us. This is our complete list of Part A recipients; a current subprocessor list covering
        Customer Data is in <a href="#b-subprocessors">Part B</a>.
      </p>

      <table>
        <thead>
          <tr>
            <th>Recipient</th>
            <th>What it receives</th>
            <th>When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Amazon Web Services</td>
            <td>Hosting and storage for our infrastructure; therefore all data we hold</td>
            <td>Always, on Laminar Cloud</td>
          </tr>
          <tr>
            <td>Stripe</td>
            <td>Billing contact details, workspace identifier, subscription and usage amounts; payment details</td>
            <td>Paid plans on Laminar Cloud</td>
          </tr>
          <tr>
            <td>PostHog</td>
            <td>Product analytics events and session replay, keyed to your email address; self-hosted heartbeats</td>
            <td>When analytics is enabled</td>
          </tr>
          <tr>
            <td>Sentry</td>
            <td>Error reports, stack traces and performance traces</td>
            <td>Laminar Cloud</td>
          </tr>
          <tr>
            <td>Resend</td>
            <td>Recipient email address and the content of transactional emails, alerts and reports we send you</td>
            <td>When email delivery is configured</td>
          </tr>
          <tr>
            <td>Loops</td>
            <td>Name, email address and signup date, for our marketing audience</td>
            <td>Laminar Cloud, on account creation</td>
          </tr>
          <tr>
            <td>Slack</td>
            <td>Alert and report content delivered to a workspace channel you connect</td>
            <td>When you connect Slack</td>
          </tr>
          <tr>
            <td>Your identity provider</td>
            <td>The sign-in handshake; we receive your profile data from them</td>
            <td>When you use single sign-on</td>
          </tr>
        </tbody>
      </table>

      <p>
        We also disclose personal data (a) to professional advisers, auditors and insurers; (b) where required by law,
        legal process or a lawful request from a public authority; (c) to establish, exercise or defend legal claims;
        and (d) in connection with a merger, financing, acquisition, reorganisation or sale of assets, in which case we
        will require the recipient to honour this notice or give you notice before your data becomes subject to a
        different one.
      </p>

      <h3 id="a-transfers">A.5 International transfers</h3>

      <p>
        Laminar is established in the United States and our hosted infrastructure and service providers are primarily
        located there. If you are in the European Economic Area, the United Kingdom or Switzerland, your personal data
        will be transferred to the United States. Where we rely on the EU Standard Contractual Clauses, the UK
        International Data Transfer Addendum, or another Article 46 mechanism for a given recipient, we will identify it
        on request to <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a>. The specific mechanism in place for each
        recipient is being confirmed and will be published here.
      </p>

      <h3 id="a-retention">A.6 How long we keep it</h3>

      <p>
        We keep Part A personal data for as long as we need it for the purpose it was collected for, and then for any
        additional period the law requires. Specifically:
      </p>

      <ul>
        <li>
          <strong>Account, workspace and membership data</strong> — for the life of the account, and afterwards only
          where we need it for the reasons below.
        </li>
        <li>
          <strong>Session and device-authorization records</strong> — these carry an expiry after which they are no
          longer valid for authentication. We do not currently run an automated job that removes expired session rows,
          so an expired record may persist in the database beyond its expiry.
        </li>
        <li>
          <strong>API credentials</strong> — until you delete the key, or, where you set an expiry, until the key is
          next presented after expiring, at which point it is deleted.
        </li>
        <li>
          <strong>Billing and usage records</strong> — for the life of the account and then as long as tax, accounting
          and audit obligations require, typically seven years.
        </li>
        <li>
          <strong>Support and sales correspondence</strong> — for as long as needed to handle the matter and maintain
          the customer relationship.
        </li>
        <li>
          <strong>Analytics, error monitoring and telemetry data</strong> — retained according to the configuration of
          the relevant provider. These retention periods are set in the provider&apos;s own console rather than in our
          code; we are documenting them and will state them here.
        </li>
      </ul>

      <p>
        We may retain personal data longer than the periods above where necessary to comply with law, resolve disputes,
        prevent fraud and abuse, or enforce our agreements. Data may also persist in encrypted backups after deletion
        from our live systems until those backups age out; our backup retention and purge schedule is being documented
        and will be stated here.
      </p>

      <h3 id="a-rights">A.7 Your rights</h3>

      <p>
        Depending on where you live, you may have some or all of the following rights in respect of Part A personal
        data: to know what we process and access a copy of it; to correct inaccuracies; to delete it; to receive it in a
        portable format; to restrict or object to processing; to withdraw consent; to opt out of targeted advertising,
        sale, or profiling with legal effects; and not to be discriminated against for exercising a right.
      </p>

      <p>
        Exercise any of these by emailing <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a>. We will verify your
        identity against data we already hold before acting, and we will respond within the period applicable law
        requires. You may use an authorised agent where the law allows; we may ask for proof of authorisation. If we
        decline your request you may appeal by replying to our response, and we will explain our decision in writing.
      </p>

      <p>
        <strong>Deleting your account.</strong> There is currently no self-service way to delete a Laminar account in
        the product. Email <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a> and we will action it. Note that if you
        are the sole owner of a workspace, we will need to establish what should happen to that workspace and its data
        before we can close your account. Workspace owners can delete a workspace from workspace settings, which deletes
        its projects and the trace data stored for them.
      </p>

      <p>
        <strong>Marketing.</strong> Unsubscribe using the link in any marketing email, or email us. We will still send
        you service and billing notices, which are not marketing.
      </p>

      <p id="a-us">
        <strong>US state privacy laws.</strong> We collect the following categories of personal data under the
        California Consumer Privacy Act taxonomy: identifiers (name, email, account name, IP address, online
        identifiers); commercial information (subscription and transaction records); internet or network activity
        (product usage, page views, session replay of our own web app); and geolocation inferred from IP address at a
        coarse level. We do not collect biometric data, education records, or protected classification characteristics
        in Part A, and we do not knowingly collect Part A personal data from children.
      </p>

      <p>
        In the preceding twelve months we have disclosed personal data to service providers for the business purposes
        described in <a href="#a-purposes">A.3</a>. <strong>We have not sold personal data</strong> and{" "}
        <strong>we have not shared personal data for cross-context behavioural advertising.</strong>
      </p>

      <p>
        <strong>Sensitive personal information.</strong> We do not collect sensitive personal information for Part A
        purposes, and we do not use or disclose it for purposes that would trigger a right to limit under California
        law. Customer Data is a different matter and is addressed in <a href="#b-sensitive">Part B</a>; where Customer
        Data contains sensitive personal information, Laminar handles it as a service provider on the customer&apos;s
        instructions and the customer is the business.
      </p>

      <p>
        <strong>EEA, UK and Swiss residents.</strong> You have the right to lodge a complaint with your supervisory
        authority — your{" "}
        <a
          href="https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm"
          target="_blank"
          rel="noreferrer"
        >
          EU member state authority
        </a>
        , the{" "}
        <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">
          UK Information Commissioner&apos;s Office
        </a>
        , or the{" "}
        <a href="https://www.edoeb.admin.ch/edoeb/en/home.html" target="_blank" rel="noreferrer">
          Swiss Federal Data Protection and Information Commissioner
        </a>
        .
      </p>

      <h3 id="a-cookies">A.8 Cookies and tracking</h3>

      <p>
        We use cookies and similar technologies to keep you signed in, remember preferences, and — where enabled —
        collect the product analytics described above. Details and your choices are in our{" "}
        <a href={withBasePath("/policies/cookies")}>Cookie Notice</a>. Because there is still no consensus standard for
        honouring browser Do-Not-Track signals, we do not currently respond to them; we will update this notice if that
        changes.
      </p>

      <h3 id="a-children">A.9 Children</h3>

      <p>
        The Services are for business use and are not directed to children. We do not knowingly collect personal data
        from anyone under 18. If you believe a child has given us personal data, email{" "}
        <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a> and we will delete it.
      </p>

      <h3 id="a-security">A.10 Security</h3>

      <p>
        We maintain technical and organisational measures intended to protect personal data, including encryption in
        transit, access controls scoped to workspace membership, hashed API credentials, and encryption of third-party
        integration tokens at rest. No system is perfectly secure, and we cannot guarantee that our safeguards will
        never be defeated.
      </p>

      {/* ------------------------------------------------------------------ */}

      <h2 id="part-b">PART B — CUSTOMER DATA LAMINAR PROCESSES FOR CUSTOMERS</h2>

      <p>
        &quot;<strong>Customer Data</strong>&quot; means the data a customer or its end users transmit to the platform
        for processing: traces and spans and their attributes, the language-model prompts and completions recorded on
        those spans, tool definitions and tool call records, browser session recordings, evaluation runs and their
        inputs, outputs and scores, datasets and dataset records, labelling queue items, and derived artefacts the
        platform computes from any of these.
      </p>

      <p>
        For Customer Data, <strong>the customer is the controller and Laminar is the processor.</strong> The customer
        chooses what to instrument and therefore what reaches us; we process it to provide the platform and on the
        customer&apos;s documented instructions. This processing is governed by our Data Processing Addendum, which
        forms part of the customer&apos;s agreement with us and which prevails over this Part in the event of any
        conflict.
      </p>

      <h3 id="b-what">B.1 What Customer Data contains</h3>

      <p>
        This is the point the previous version of this notice got wrong, so we state it plainly. Agent traces contain
        whatever the customer&apos;s application put in front of a language model and whatever came back. In practice
        that routinely includes free-text input written by the customer&apos;s end users. We cannot constrain what
        appears in it.
      </p>

      <p>The platform stores, per customer project:</p>

      <ul>
        <li>
          <strong>Spans</strong> — span and trace identifiers, names, timing, span type, status, the span&apos;s input
          and output, arbitrary customer-set attributes, session and user identifiers the customer chooses to attach,
          model and provider names, token counts and computed cost, tags, span events including exception messages and
          stack traces, and trace-level metadata. Stored in our analytics database.
        </li>
        <li>
          <strong>Language-model message content</strong> — the prompt and completion messages recorded on spans. To
          avoid storing the same conversation history once per span, message bodies are content-addressed and stored
          once per project in a shared content table, with spans referencing them by hash. The raw message text lives in
          that table.
        </li>
        <li>
          <strong>Trace-level rollups and derived artefacts</strong> — aggregated trace statistics, a truncated preview
          of the trace&apos;s first input and last output, extracted &quot;user task&quot; and trace-output values, and,
          where the customer uses those features, generated summaries and analyses. Stored alongside the span data.
        </li>
        <li>
          <strong>Browser session recordings</strong> — where the customer enables session recording, the raw rrweb
          event payloads captured from the customer&apos;s web application, with timestamps and session and trace
          identifiers. Stored in our analytics database, not in object storage.
        </li>
        <li>
          <strong>Evaluation and dataset data</strong> — evaluation names and metadata, per-datapoint inputs, targets,
          executor outputs and scores, dataset records, and labelling queue items with their payloads and annotations.
        </li>
        <li>
          <strong>Binary payloads</strong> — where a span references an image, PDF or similar attachment, the object
          itself is held in our object storage under a project-scoped key, and the span holds a pointer to it. Dataset
          exports are also written to object storage.
        </li>
        <li>
          <strong>Search index</strong> — span input, output and attributes, span events, and signal event payloads are
          indexed into our search engine so that full-text search works. The indexed text is a copy of the content, held
          in the index.
        </li>
        <li>
          <strong>Queues and caches</strong> — during ingestion, spans pass through a durable message queue before being
          written to storage. Short-lived caches hold content hashes and, for search autocomplete, span names and tags.
        </li>
      </ul>

      <p id="b-sensitive">
        <strong>Sensitive and special-category data.</strong> Because trace content is arbitrary end-user text, it can
        contain special-category data within the meaning of GDPR Article 9, sensitive personal information under US
        state laws, or data subject to sector-specific rules. Laminar does not seek this data and does not process it
        for any purpose of its own beyond providing the platform. Customers should not send us special-category data
        without having a lawful basis for it, having covered it in their own notices, and having agreed the necessary
        terms with us. We do not undertake to identify, classify or specially handle special-category data within
        Customer Data unless we have agreed to in writing.
      </p>

      <h3 id="b-source">B.2 Where Customer Data comes from</h3>

      <p>
        Laminar receives Customer Data from the customer&apos;s systems, not from the individuals it describes. Where
        Customer Data contains personal data about a customer&apos;s end users, Laminar has not collected it from those
        individuals and typically has no relationship with them and no means of contacting them. For the customer, this
        is data obtained from a source other than the data subject; the customer&apos;s own notice obligations to its
        end users, including under GDPR Article 14 where applicable, are the customer&apos;s responsibility.
      </p>

      <h3 id="b-purposes">B.3 What we do with it</h3>

      <p>We process Customer Data only:</p>

      <ul>
        <li>
          to provide the platform — ingest, store, index, search, aggregate, visualise and serve it back to the
          customer;
        </li>
        <li>
          to run the features the customer enables, including evaluations, signals and alerting, and AI-assisted
          features the customer invokes;
        </li>
        <li>to deliver alerts and reports to the destinations the customer configures;</li>
        <li>to maintain, secure, troubleshoot and prevent abuse of the platform;</li>
        <li>to comply with law; and</li>
        <li>
          where and only where the customer has turned Privacy Mode off, to improve Laminar&apos;s own models as
          described in <a href="#b-training">B.6</a>.
        </li>
      </ul>

      <p>
        Laminar personnel access Customer Data only where necessary for these purposes — principally to investigate a
        support request or an incident — under access controls and confidentiality obligations.
      </p>

      <h3 id="b-subprocessors">B.4 Subprocessors and other recipients</h3>

      <p>
        The following third parties may process Customer Data. Whether a given one is engaged depends on the
        customer&apos;s deployment and configuration; those marked opt-in are only engaged when the customer or the
        operator turns the relevant feature on.
      </p>

      <table>
        <thead>
          <tr>
            <th>Recipient</th>
            <th>What it receives</th>
            <th>Engaged</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Amazon Web Services</td>
            <td>
              Hosting, databases, message queue, search index and object storage — therefore all Customer Data on
              Laminar Cloud
            </td>
            <td>Always, on Laminar Cloud</td>
          </tr>
          <tr>
            <td>Amazon Bedrock (AWS)</td>
            <td>
              Span input and output, prompts and messages sent to a model for an AI-assisted feature, including our
              default configuration for those features
            </td>
            <td>When the AI provider is configured to Bedrock</td>
          </tr>
          <tr>
            <td>OpenAI</td>
            <td>
              Span input and output, prompts and messages sent to a model for an AI-assisted feature; text sent for
              embedding
            </td>
            <td>Opt-in — when the AI provider is configured to OpenAI</td>
          </tr>
          <tr>
            <td>Google</td>
            <td>Span input and output, prompts and messages sent to a model for an AI-assisted feature</td>
            <td>Opt-in — when the AI provider is configured to Gemini</td>
          </tr>
          <tr>
            <td>Slack</td>
            <td>
              Alert and report content, which includes generated summaries of trace content, event names and trace
              identifiers
            </td>
            <td>Opt-in — when the workspace connects Slack</td>
          </tr>
          <tr>
            <td>Resend</td>
            <td>
              Report and alert emails, which include generated summaries of trace content and event names, sent to
              addresses the customer configures
            </td>
            <td>When email delivery is configured</td>
          </tr>
          <tr>
            <td>Sentry</td>
            <td>
              Error reports and stack traces from our services. Not a Customer Data destination by design, but a report
              can incidentally include fragments of the data the failing request was handling
            </td>
            <td>Laminar Cloud</td>
          </tr>
        </tbody>
      </table>

      <p>
        <strong>Model providers the customer brings itself.</strong> Where a customer stores its own provider
        credentials in Laminar and uses the playground or a provider-backed feature, requests go to that provider —
        Anthropic, OpenAI, Google, Azure OpenAI, Groq or Mistral, as applicable — under the customer&apos;s own account
        and that provider&apos;s terms. Laminar transmits the request; the customer chooses the provider.
      </p>

      <p>
        We maintain the current subprocessor list and give notice of additions as our Data Processing Addendum requires.
        Ask <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a> for the current list and to subscribe to change
        notifications.
      </p>

      <h3 id="b-retention">B.5 How long Customer Data is kept, and what deletion does</h3>

      <p>
        We would rather state this accurately than favourably, because the distinction matters for anyone relying on it.
      </p>

      <p>
        <strong>Storage is not time-limited by default.</strong> Customer Data written to our analytics database is
        retained until it is deleted by a customer action or by us. With one exception, our storage tables carry no
        automatic expiry: intermediate signal run messages expire seven days after they are written, and our search
        index applies a 90-day retention policy to indexed span, event and signal-event documents. Everything else
        persists until deleted.
      </p>

      <p>
        <strong>Plan retention windows limit access, not storage.</strong> Paid plan tiers carry a data retention window
        — currently 7 days on the free tier, 30 days on Starter, and 6 months on Pro, with enterprise agreements set
        individually. That window is enforced as an access control: a request for data older than the window is refused.
        It is <strong>not</strong> a deletion. Data older than a plan&apos;s window remains in storage and becomes
        reachable again if the plan changes. Do not read the plan retention window as a retention limit in the
        data-protection sense.
      </p>

      <p>
        <strong>Deleting a project</strong> deletes the project&apos;s records from our primary database and issues
        deletes across the analytics tables holding that project&apos;s spans, traces, message content, session
        recordings, evaluation and dataset data, labelling queue items and notifications. In our analytics database
        these are asynchronous operations: they are accepted immediately and the underlying storage is rewritten
        afterwards. Project deletion does <strong>not</strong> currently remove the project&apos;s documents from the
        search index, and does not delete binary payloads or dataset exports from object storage; indexed documents age
        out under the 90-day index retention policy, and we are closing the object-storage gap.
      </p>

      <p>
        <strong>Deleting a workspace</strong> deletes each of its projects as above, cancels any subscription, and
        deletes the workspace record. The same search-index and object-storage caveats apply.
      </p>

      <p>
        <strong>Deleting an individual trace or span</strong> removes the span records from the primary span store. It
        does not currently remove the trace-level rollup row — which includes the truncated input and output previews
        and extracted metadata — the deduplicated message bodies, session recordings, or the corresponding search index
        entries. A customer that needs a specific trace fully expunged should contact us so we can do it properly, and
        should not rely on the in-product delete for that purpose.
      </p>

      <p>
        <strong>Backups.</strong> Customer Data may persist in backups and snapshots after deletion from live systems.
        Our backup retention and purge schedule is being documented and will be stated here.
      </p>

      <p>
        On termination, we delete or return Customer Data on the terms set out in the Data Processing Addendum. A
        customer wanting deletion to reach the gaps identified above should ask us to confirm completion in writing.
      </p>

      <h3 id="b-training">B.6 Model improvement — training on Customer Data</h3>

      <p>
        Laminar is building models that make the product better at understanding agent traces. Training those models on
        real traces is what makes them useful. Training is governed by a single control:
      </p>

      <p>
        <strong>Privacy Mode is on by default.</strong> Every workspace starts with Privacy Mode enabled. While Privacy
        Mode is on for a workspace,{" "}
        <strong>
          Laminar does not use that workspace&apos;s Customer Data to train, fine-tune or otherwise improve any Laminar
          model,
        </strong>{" "}
        and does not include it in any training corpus.
      </p>

      <p>
        A workspace owner can turn Privacy Mode off in workspace settings. Turning it off is what permits Laminar to use
        that workspace&apos;s Customer Data for model improvement, under the licence granted in our Terms of Service and
        subject to the following, which apply whether or not Privacy Mode is off:
      </p>

      <ul>
        <li>
          <strong>Redaction on the training path is mandatory.</strong> Customer Data is redacted before it enters a
          training corpus, regardless of whether the customer has enabled redaction at ingestion. A customer who has not
          enabled ingest-time redaction does not thereby end up with unredacted content in a training corpus. Redaction
          is an automated detection step; see the limits in <a href="#b-redaction">B.7</a>.
        </li>
        <li>
          <strong>Self-hosted and single-tenant data-plane deployments are excluded.</strong> We do not receive
          self-hosted Customer Data at all, and Customer Data held in a customer&apos;s own data plane is never part of
          a training corpus, irrespective of the Privacy Mode setting.
        </li>
        <li>
          <strong>Opting back in to Privacy Mode is prospective only.</strong> Re-enabling Privacy Mode stops future use
          of the workspace&apos;s Customer Data for training. It does not remove data already incorporated into a
          training corpus, and{" "}
          <strong>
            it cannot remove the influence of that data from model weights already trained — that is not technically
            reversible.
          </strong>{" "}
          The same is true of a deletion request that arrives after training has occurred.
        </li>
        <li>
          <strong>Inference is separate from training.</strong> AI-assisted features send Customer Data to the model
          providers listed in <a href="#b-subprocessors">B.4</a> at the time the feature runs. That happens
          independently of Privacy Mode, because it is how the feature works. We contract with those providers on terms
          intended to prevent them training their own models on data we send; the customer&apos;s own provider
          credentials, where used, are governed by the customer&apos;s agreement with that provider instead.
        </li>
      </ul>

      <p>
        Where the GDPR applies, model improvement is a purpose the customer, as controller, must have a lawful basis
        for; by turning Privacy Mode off, the customer instructs us to process its Customer Data for that purpose and
        confirms it has that basis. See <a href={withBasePath("/policies/data-use")}>Data use</a> for the plain-English
        version.
      </p>

      <h3 id="b-redaction">B.7 Redaction, and what it does not cover</h3>

      <p>
        Laminar can run ingested spans through an automated PII detection and redaction step. Being accurate about its
        scope matters more than making it sound comprehensive.
      </p>

      <ul>
        <li>
          <strong>Ingest-time redaction is off by default</strong> and is enabled per project. It requires the
          deployment to be running the redaction service. On Laminar Cloud it is available on Pro and enterprise plans.
        </li>
        <li>
          <strong>What it covers:</strong> a span&apos;s input and output, the deduplicated language-model message
          bodies, and tool definitions.
        </li>
        <li>
          <strong>What it does not cover:</strong> span attributes, span events including exception messages and stack
          traces, span names, trace-level metadata, the truncated trace input and output previews stored on the trace
          rollup, extracted trace input and output values, evaluation and dataset data, labelling queue items, browser
          session recordings, and binary payloads in object storage.
        </li>
        <li>
          <strong>It is forward-looking only.</strong> Enabling redaction does not alter content already stored, and
          message bodies already stored for a project are not re-processed.
        </li>
        <li>
          <strong>It is best-effort and fails open.</strong> If the redaction service is unavailable, times out, or
          rejects a payload — including where a payload exceeds its size limits — the span is stored{" "}
          <strong>unredacted</strong> rather than dropped, so that observability data is not lost. Ingestion is never
          blocked on redaction.
        </li>
        <li>
          <strong>Detection is probabilistic.</strong> It is a machine-learning model, not a rule set, with no
          guaranteed recall. It operates on string values, so JSON keys, numbers and booleans are not redacted, certain
          structural fields are excluded by design, and deeply nested values beyond a fixed depth are not walked. The
          model and its label set are configurable per deployment.
        </li>
        <li>
          <strong>The pre-redaction payload exists transiently.</strong> Redaction runs after a span has been accepted
          and queued, so unredacted content is present in the durable ingestion queue until it is consumed.
        </li>
      </ul>

      <p>
        Treat redaction as risk reduction, not as a guarantee that Customer Data is free of personal data. Customers who
        must keep specific categories of data out of Laminar should filter at the source, in their own instrumentation.
      </p>

      <h3 id="b-data-subjects">B.8 End-user data subjects and their requests</h3>

      <p>
        If you are an individual whose personal data may appear inside a Laminar customer&apos;s traces,{" "}
        <strong>please contact that customer, not us.</strong> They decided to collect the data and to send it to us;
        under data protection law they are the controller and we act only on their instructions. We generally have no
        way to identify which traces relate to you, and no relationship with you that would let us verify a request.
      </p>

      <p>
        Where a customer asks us to help it respond to an access, correction, deletion, restriction, objection or
        portability request from one of its end users, we assist as the Data Processing Addendum requires. If an
        end-user request reaches us directly, we will not act on it ourselves; we will refer you to the customer and,
        where we can identify them and it is appropriate, notify them.
      </p>

      <h3 id="b-security">B.9 Security and incidents</h3>

      <p>
        Customer Data is segregated by project and workspace, and access is scoped to workspace membership and
        project-scoped API credentials. Ingestion credentials are stored hashed. We notify customers of a personal data
        breach affecting their Customer Data on the terms and within the timeframes set out in the Data Processing
        Addendum.
      </p>

      {/* ------------------------------------------------------------------ */}

      <h2 id="changes">CHANGES TO THIS NOTICE</h2>

      <p>
        We update this notice as our practices and the law change. The &quot;Last updated&quot; date above reflects the
        current version. Where a change materially affects how we handle personal data, we will give notice through the
        product or by email before it takes effect. A change that would expand our use of Customer Data for model
        improvement beyond what is described in <a href="#b-training">B.6</a> will not be applied to a workspace without
        a fresh choice by that workspace.
      </p>

      <h2 id="contact">HOW TO CONTACT US</h2>

      <p>
        Privacy enquiries and rights requests: <a href="mailto:privacy@lmnr.ai">privacy@lmnr.ai</a>.
      </p>

      <p>
        General enquiries: <a href="mailto:founders@lmnr.ai">founders@lmnr.ai</a>.
      </p>

      <p>By post: LMNR AI, Inc., 2261 Market Street, STE 10826, San Francisco, CA 94114, United States.</p>

      <p>
        Our data protection contact details, including any Data Protection Officer appointment and any representative
        appointed under GDPR Article 27 for individuals in the European Economic Area or the United Kingdom, are being
        confirmed and will be published here.
      </p>

      <p>
        See also our <a href={withBasePath("/policies/terms")}>Terms of Service</a>,{" "}
        <a href={withBasePath("/policies/data-use")}>Data use</a> summary, and{" "}
        <a href={withBasePath("/policies/cookies")}>Cookie Notice</a>.
      </p>
    </div>
  );
}
