CREATE TABLE IF NOT EXISTS spans_v2
(
    `span_id` UUID,
    `name` String,
    `span_type` UInt8,
    `start_time` DateTime64(9, 'UTC'),
    `end_time` DateTime64(9, 'UTC'),
    `input_cost` Float64,
    `output_cost` Float64,
    `total_cost` Float64,
    `model` String,
    `session_id` String,
    `project_id` UUID,
    `trace_id` UUID,
    `provider` String,
    `input_tokens` Int64,
    `output_tokens` Int64,
    `total_tokens` Int64,
    `user_id` String,
    `path` String,
    `input` String CODEC(ZSTD(3)),
    `output` String CODEC(ZSTD(3)),
    `size_bytes` UInt64 DEFAULT 0,
    `status` String,
    `attributes` String,
    `request_model` String,
    `response_model` String,
    `parent_span_id` UUID,
    `trace_metadata` String,
    `trace_type` UInt8,
    `tags_array` Array(String) DEFAULT [],
    `events` Array(Tuple(
        timestamp Int64,
        name String,
        attributes String)),
    INDEX idx_project_span (project_id, span_id) TYPE bloom_filter GRANULARITY 1,
    INDEX spans_parent_span_id_bf_idx (project_id, trace_id, parent_span_id) TYPE bloom_filter GRANULARITY 1,
    PROJECTION spans_no_io_by_start_time (
        SELECT
            span_id,
            name,
            span_type,
            start_time,
            end_time,
            input_cost,
            output_cost,
            total_cost,
            model,
            session_id,
            project_id,
            trace_id,
            provider,
            input_tokens,
            output_tokens,
            total_tokens,
            user_id,
            path,
            SUBSTRING(`input`, 500) AS input_preview,
            SUBSTRING(`output`, 500) AS output_preview,
            size_bytes,
            status,
            attributes,
            request_model,
            response_model,
            parent_span_id,
            trace_metadata,
            trace_type,
            tags_array,
            events
        ORDER BY project_id, start_time, trace_id, span_id
    )
)
ENGINE = MergeTree
ORDER BY (project_id, trace_id, start_time, span_id)
SETTINGS index_granularity = 8192;

INSERT INTO spans_v2 (
    span_id,
    name,
    span_type,
    start_time,
    end_time,
    input_cost,
    output_cost,
    total_cost,
    model,
    session_id,
    project_id,
    trace_id,
    provider,
    input_tokens,
    output_tokens,
    total_tokens,
    user_id,
    path,
    input,
    output,
    size_bytes,
    status,
    attributes,
    request_model,
    response_model,
    parent_span_id,
    trace_metadata,
    trace_type,
    tags_array,
    events
) SELECT
    span_id,
    name,
    span_type,
    start_time,
    end_time,
    input_cost,
    output_cost,
    total_cost,
    model,
    session_id,
    project_id,
    trace_id,
    provider,
    input_tokens,
    output_tokens,
    total_tokens,
    user_id,
    path,
    input,
    output,
    size_bytes,
    status,
    attributes,
    request_model,
    response_model,
    parent_span_id,
    trace_metadata,
    trace_type,
    tags_array,
    events
FROM spans;

RENAME TABLE spans TO old_spans;
RENAME TABLE spans_v2 TO spans;
DROP TABLE IF EXISTS old_spans;
